/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.23.0
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * One ad schedule window as Google stores it. Half-open: it is exclusive of the end minute, so 09:00-12:00 and 12:00-17:00 are adjacent, not overlapping.
 */
@JsonPropertyOrder({
  AdScheduleWindow.JSON_PROPERTY_CRITERION_ID,
  AdScheduleWindow.JSON_PROPERTY_RESOURCE_NAME,
  AdScheduleWindow.JSON_PROPERTY_DAY_OF_WEEK,
  AdScheduleWindow.JSON_PROPERTY_START_HOUR,
  AdScheduleWindow.JSON_PROPERTY_START_MINUTE,
  AdScheduleWindow.JSON_PROPERTY_END_HOUR,
  AdScheduleWindow.JSON_PROPERTY_END_MINUTE,
  AdScheduleWindow.JSON_PROPERTY_BID_MODIFIER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-18T10:47:03.391175356Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class AdScheduleWindow {
  public static final String JSON_PROPERTY_CRITERION_ID = "criterionId";
  @javax.annotation.Nullable
  private String criterionId;

  public static final String JSON_PROPERTY_RESOURCE_NAME = "resourceName";
  @javax.annotation.Nullable
  private String resourceName;

  /**
   * Gets or Sets dayOfWeek
   */
  public enum DayOfWeekEnum {
    MONDAY(String.valueOf("MONDAY")),
    
    TUESDAY(String.valueOf("TUESDAY")),
    
    WEDNESDAY(String.valueOf("WEDNESDAY")),
    
    THURSDAY(String.valueOf("THURSDAY")),
    
    FRIDAY(String.valueOf("FRIDAY")),
    
    SATURDAY(String.valueOf("SATURDAY")),
    
    SUNDAY(String.valueOf("SUNDAY"));

    private String value;

    DayOfWeekEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DayOfWeekEnum fromValue(String value) {
      for (DayOfWeekEnum b : DayOfWeekEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DAY_OF_WEEK = "dayOfWeek";
  @javax.annotation.Nullable
  private DayOfWeekEnum dayOfWeek;

  public static final String JSON_PROPERTY_START_HOUR = "startHour";
  @javax.annotation.Nullable
  private Integer startHour;

  /**
   * Gets or Sets startMinute
   */
  public enum StartMinuteEnum {
    NUMBER_0(Integer.valueOf(0)),
    
    NUMBER_15(Integer.valueOf(15)),
    
    NUMBER_30(Integer.valueOf(30)),
    
    NUMBER_45(Integer.valueOf(45));

    private Integer value;

    StartMinuteEnum(Integer value) {
      this.value = value;
    }

    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StartMinuteEnum fromValue(Integer value) {
      for (StartMinuteEnum b : StartMinuteEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_START_MINUTE = "startMinute";
  @javax.annotation.Nullable
  private StartMinuteEnum startMinute;

  public static final String JSON_PROPERTY_END_HOUR = "endHour";
  @javax.annotation.Nullable
  private Integer endHour;

  /**
   * Gets or Sets endMinute
   */
  public enum EndMinuteEnum {
    NUMBER_0(Integer.valueOf(0)),
    
    NUMBER_15(Integer.valueOf(15)),
    
    NUMBER_30(Integer.valueOf(30)),
    
    NUMBER_45(Integer.valueOf(45));

    private Integer value;

    EndMinuteEnum(Integer value) {
      this.value = value;
    }

    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EndMinuteEnum fromValue(Integer value) {
      for (EndMinuteEnum b : EndMinuteEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_END_MINUTE = "endMinute";
  @javax.annotation.Nullable
  private EndMinuteEnum endMinute;

  public static final String JSON_PROPERTY_BID_MODIFIER = "bidModifier";
  private JsonNullable<BigDecimal> bidModifier = JsonNullable.<BigDecimal>undefined();

  public AdScheduleWindow() { 
  }

  public AdScheduleWindow criterionId(@javax.annotation.Nullable String criterionId) {
    this.criterionId = criterionId;
    return this;
  }

  /**
   * Google campaign criterion id. Changes whenever the window is rewritten, because Google cannot edit a schedule in place.
   * @return criterionId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CRITERION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCriterionId() {
    return criterionId;
  }


  @JsonProperty(value = JSON_PROPERTY_CRITERION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCriterionId(@javax.annotation.Nullable String criterionId) {
    this.criterionId = criterionId;
  }


  public AdScheduleWindow resourceName(@javax.annotation.Nullable String resourceName) {
    this.resourceName = resourceName;
    return this;
  }

  /**
   * Get resourceName
   * @return resourceName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESOURCE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getResourceName() {
    return resourceName;
  }


  @JsonProperty(value = JSON_PROPERTY_RESOURCE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResourceName(@javax.annotation.Nullable String resourceName) {
    this.resourceName = resourceName;
  }


  public AdScheduleWindow dayOfWeek(@javax.annotation.Nullable DayOfWeekEnum dayOfWeek) {
    this.dayOfWeek = dayOfWeek;
    return this;
  }

  /**
   * Get dayOfWeek
   * @return dayOfWeek
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DAY_OF_WEEK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DayOfWeekEnum getDayOfWeek() {
    return dayOfWeek;
  }


  @JsonProperty(value = JSON_PROPERTY_DAY_OF_WEEK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDayOfWeek(@javax.annotation.Nullable DayOfWeekEnum dayOfWeek) {
    this.dayOfWeek = dayOfWeek;
  }


  public AdScheduleWindow startHour(@javax.annotation.Nullable Integer startHour) {
    this.startHour = startHour;
    return this;
  }

  /**
   * Get startHour
   * minimum: 0
   * maximum: 23
   * @return startHour
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_HOUR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getStartHour() {
    return startHour;
  }


  @JsonProperty(value = JSON_PROPERTY_START_HOUR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartHour(@javax.annotation.Nullable Integer startHour) {
    this.startHour = startHour;
  }


  public AdScheduleWindow startMinute(@javax.annotation.Nullable StartMinuteEnum startMinute) {
    this.startMinute = startMinute;
    return this;
  }

  /**
   * Get startMinute
   * @return startMinute
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_MINUTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StartMinuteEnum getStartMinute() {
    return startMinute;
  }


  @JsonProperty(value = JSON_PROPERTY_START_MINUTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartMinute(@javax.annotation.Nullable StartMinuteEnum startMinute) {
    this.startMinute = startMinute;
  }


  public AdScheduleWindow endHour(@javax.annotation.Nullable Integer endHour) {
    this.endHour = endHour;
    return this;
  }

  /**
   * 24 means midnight at the end of the day.
   * minimum: 0
   * maximum: 24
   * @return endHour
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_END_HOUR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getEndHour() {
    return endHour;
  }


  @JsonProperty(value = JSON_PROPERTY_END_HOUR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndHour(@javax.annotation.Nullable Integer endHour) {
    this.endHour = endHour;
  }


  public AdScheduleWindow endMinute(@javax.annotation.Nullable EndMinuteEnum endMinute) {
    this.endMinute = endMinute;
    return this;
  }

  /**
   * Get endMinute
   * @return endMinute
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_END_MINUTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EndMinuteEnum getEndMinute() {
    return endMinute;
  }


  @JsonProperty(value = JSON_PROPERTY_END_MINUTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndMinute(@javax.annotation.Nullable EndMinuteEnum endMinute) {
    this.endMinute = endMinute;
  }


  public AdScheduleWindow bidModifier(@javax.annotation.Nullable BigDecimal bidModifier) {
    this.bidModifier = JsonNullable.<BigDecimal>of(bidModifier);
    return this;
  }

  /**
   * Bid adjustment for this window, 0.1-10.0. Null when the window runs at the campaign bid.
   * @return bidModifier
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public BigDecimal getBidModifier() {
        return bidModifier.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_BID_MODIFIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getBidModifier_JsonNullable() {
    return bidModifier;
  }
  
  @JsonProperty(JSON_PROPERTY_BID_MODIFIER)
  public void setBidModifier_JsonNullable(JsonNullable<BigDecimal> bidModifier) {
    this.bidModifier = bidModifier;
  }

  public void setBidModifier(@javax.annotation.Nullable BigDecimal bidModifier) {
    this.bidModifier = JsonNullable.<BigDecimal>of(bidModifier);
  }


  /**
   * Return true if this AdScheduleWindow object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdScheduleWindow adScheduleWindow = (AdScheduleWindow) o;
    return Objects.equals(this.criterionId, adScheduleWindow.criterionId) &&
        Objects.equals(this.resourceName, adScheduleWindow.resourceName) &&
        Objects.equals(this.dayOfWeek, adScheduleWindow.dayOfWeek) &&
        Objects.equals(this.startHour, adScheduleWindow.startHour) &&
        Objects.equals(this.startMinute, adScheduleWindow.startMinute) &&
        Objects.equals(this.endHour, adScheduleWindow.endHour) &&
        Objects.equals(this.endMinute, adScheduleWindow.endMinute) &&
        equalsNullable(this.bidModifier, adScheduleWindow.bidModifier);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(criterionId, resourceName, dayOfWeek, startHour, startMinute, endHour, endMinute, hashCodeNullable(bidModifier));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdScheduleWindow {\n");
    sb.append("    criterionId: ").append(toIndentedString(criterionId)).append("\n");
    sb.append("    resourceName: ").append(toIndentedString(resourceName)).append("\n");
    sb.append("    dayOfWeek: ").append(toIndentedString(dayOfWeek)).append("\n");
    sb.append("    startHour: ").append(toIndentedString(startHour)).append("\n");
    sb.append("    startMinute: ").append(toIndentedString(startMinute)).append("\n");
    sb.append("    endHour: ").append(toIndentedString(endHour)).append("\n");
    sb.append("    endMinute: ").append(toIndentedString(endMinute)).append("\n");
    sb.append("    bidModifier: ").append(toIndentedString(bidModifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `criterionId` to the URL query string
    if (getCriterionId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scriterionId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCriterionId()))));
    }

    // add `resourceName` to the URL query string
    if (getResourceName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sresourceName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResourceName()))));
    }

    // add `dayOfWeek` to the URL query string
    if (getDayOfWeek() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdayOfWeek%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDayOfWeek()))));
    }

    // add `startHour` to the URL query string
    if (getStartHour() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstartHour%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStartHour()))));
    }

    // add `startMinute` to the URL query string
    if (getStartMinute() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstartMinute%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStartMinute()))));
    }

    // add `endHour` to the URL query string
    if (getEndHour() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sendHour%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndHour()))));
    }

    // add `endMinute` to the URL query string
    if (getEndMinute() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sendMinute%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndMinute()))));
    }

    // add `bidModifier` to the URL query string
    if (getBidModifier() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbidModifier%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBidModifier()))));
    }

    return joiner.toString();
  }
}

