/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * Success details (present on successful events)
 */
@JsonPropertyOrder({
  ConnectionLogSuccess.JSON_PROPERTY_DISPLAY_NAME,
  ConnectionLogSuccess.JSON_PROPERTY_USERNAME,
  ConnectionLogSuccess.JSON_PROPERTY_PROFILE_PICTURE,
  ConnectionLogSuccess.JSON_PROPERTY_PERMISSIONS,
  ConnectionLogSuccess.JSON_PROPERTY_TOKEN_EXPIRES_AT,
  ConnectionLogSuccess.JSON_PROPERTY_ACCOUNT_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:20:32.263430656Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class ConnectionLogSuccess {
  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  @javax.annotation.Nullable
  private String displayName;

  public static final String JSON_PROPERTY_USERNAME = "username";
  @javax.annotation.Nullable
  private String username;

  public static final String JSON_PROPERTY_PROFILE_PICTURE = "profilePicture";
  @javax.annotation.Nullable
  private String profilePicture;

  public static final String JSON_PROPERTY_PERMISSIONS = "permissions";
  @javax.annotation.Nullable
  private List<String> permissions = new ArrayList<>();

  public static final String JSON_PROPERTY_TOKEN_EXPIRES_AT = "tokenExpiresAt";
  @javax.annotation.Nullable
  private OffsetDateTime tokenExpiresAt;

  public static final String JSON_PROPERTY_ACCOUNT_TYPE = "accountType";
  @javax.annotation.Nullable
  private String accountType;

  public ConnectionLogSuccess() { 
  }

  public ConnectionLogSuccess displayName(@javax.annotation.Nullable String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * Get displayName
   * @return displayName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DISPLAY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(value = JSON_PROPERTY_DISPLAY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayName(@javax.annotation.Nullable String displayName) {
    this.displayName = displayName;
  }


  public ConnectionLogSuccess username(@javax.annotation.Nullable String username) {
    this.username = username;
    return this;
  }

  /**
   * Get username
   * @return username
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USERNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUsername() {
    return username;
  }


  @JsonProperty(value = JSON_PROPERTY_USERNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsername(@javax.annotation.Nullable String username) {
    this.username = username;
  }


  public ConnectionLogSuccess profilePicture(@javax.annotation.Nullable String profilePicture) {
    this.profilePicture = profilePicture;
    return this;
  }

  /**
   * Get profilePicture
   * @return profilePicture
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROFILE_PICTURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProfilePicture() {
    return profilePicture;
  }


  @JsonProperty(value = JSON_PROPERTY_PROFILE_PICTURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfilePicture(@javax.annotation.Nullable String profilePicture) {
    this.profilePicture = profilePicture;
  }


  public ConnectionLogSuccess permissions(@javax.annotation.Nullable List<String> permissions) {
    this.permissions = permissions;
    return this;
  }

  public ConnectionLogSuccess addPermissionsItem(String permissionsItem) {
    if (this.permissions == null) {
      this.permissions = new ArrayList<>();
    }
    this.permissions.add(permissionsItem);
    return this;
  }

  /**
   * OAuth scopes/permissions granted
   * @return permissions
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PERMISSIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getPermissions() {
    return permissions;
  }


  @JsonProperty(value = JSON_PROPERTY_PERMISSIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPermissions(@javax.annotation.Nullable List<String> permissions) {
    this.permissions = permissions;
  }


  public ConnectionLogSuccess tokenExpiresAt(@javax.annotation.Nullable OffsetDateTime tokenExpiresAt) {
    this.tokenExpiresAt = tokenExpiresAt;
    return this;
  }

  /**
   * Get tokenExpiresAt
   * @return tokenExpiresAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOKEN_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getTokenExpiresAt() {
    return tokenExpiresAt;
  }


  @JsonProperty(value = JSON_PROPERTY_TOKEN_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokenExpiresAt(@javax.annotation.Nullable OffsetDateTime tokenExpiresAt) {
    this.tokenExpiresAt = tokenExpiresAt;
  }


  public ConnectionLogSuccess accountType(@javax.annotation.Nullable String accountType) {
    this.accountType = accountType;
    return this;
  }

  /**
   * Account type (personal, business, organization)
   * @return accountType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAccountType() {
    return accountType;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountType(@javax.annotation.Nullable String accountType) {
    this.accountType = accountType;
  }


  /**
   * Return true if this ConnectionLog_success object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectionLogSuccess connectionLogSuccess = (ConnectionLogSuccess) o;
    return Objects.equals(this.displayName, connectionLogSuccess.displayName) &&
        Objects.equals(this.username, connectionLogSuccess.username) &&
        Objects.equals(this.profilePicture, connectionLogSuccess.profilePicture) &&
        Objects.equals(this.permissions, connectionLogSuccess.permissions) &&
        Objects.equals(this.tokenExpiresAt, connectionLogSuccess.tokenExpiresAt) &&
        Objects.equals(this.accountType, connectionLogSuccess.accountType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayName, username, profilePicture, permissions, tokenExpiresAt, accountType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectionLogSuccess {\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    profilePicture: ").append(toIndentedString(profilePicture)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    tokenExpiresAt: ").append(toIndentedString(tokenExpiresAt)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `displayName` to the URL query string
    if (getDisplayName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdisplayName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDisplayName()))));
    }

    // add `username` to the URL query string
    if (getUsername() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%susername%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUsername()))));
    }

    // add `profilePicture` to the URL query string
    if (getProfilePicture() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprofilePicture%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProfilePicture()))));
    }

    // add `permissions` to the URL query string
    if (getPermissions() != null) {
      for (int i = 0; i < getPermissions().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%spermissions%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getPermissions().get(i)))));
      }
    }

    // add `tokenExpiresAt` to the URL query string
    if (getTokenExpiresAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stokenExpiresAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTokenExpiresAt()))));
    }

    // add `accountType` to the URL query string
    if (getAccountType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saccountType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAccountType()))));
    }

    return joiner.toString();
  }
}

