/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.Post;
import dev.zernio.model.PostCreateResponse;
import dev.zernio.model.TikTokDryRunVerdict;
import dev.zernio.model.TikTokDryRunVerdictTiktokInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import dev.zernio.ApiClient;
import dev.zernio.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-09T16:17:07.976972884Z[Etc/UTC]", comments = "Generator version: 7.19.0")
@JsonDeserialize(using = CreatePost200Response.CreatePost200ResponseDeserializer.class)
@JsonSerialize(using = CreatePost200Response.CreatePost200ResponseSerializer.class)
public class CreatePost200Response extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(CreatePost200Response.class.getName());

    public static class CreatePost200ResponseSerializer extends StdSerializer<CreatePost200Response> {
        public CreatePost200ResponseSerializer(Class<CreatePost200Response> t) {
            super(t);
        }

        public CreatePost200ResponseSerializer() {
            this(null);
        }

        @Override
        public void serialize(CreatePost200Response value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class CreatePost200ResponseDeserializer extends StdDeserializer<CreatePost200Response> {
        public CreatePost200ResponseDeserializer() {
            this(CreatePost200Response.class);
        }

        public CreatePost200ResponseDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public CreatePost200Response deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize PostCreateResponse
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (PostCreateResponse.class.equals(Integer.class) || PostCreateResponse.class.equals(Long.class) || PostCreateResponse.class.equals(Float.class) || PostCreateResponse.class.equals(Double.class) || PostCreateResponse.class.equals(Boolean.class) || PostCreateResponse.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((PostCreateResponse.class.equals(Integer.class) || PostCreateResponse.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((PostCreateResponse.class.equals(Float.class) || PostCreateResponse.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (PostCreateResponse.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (PostCreateResponse.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(PostCreateResponse.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'PostCreateResponse'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'PostCreateResponse'", e);
            }

            // deserialize TikTokDryRunVerdict
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (TikTokDryRunVerdict.class.equals(Integer.class) || TikTokDryRunVerdict.class.equals(Long.class) || TikTokDryRunVerdict.class.equals(Float.class) || TikTokDryRunVerdict.class.equals(Double.class) || TikTokDryRunVerdict.class.equals(Boolean.class) || TikTokDryRunVerdict.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((TikTokDryRunVerdict.class.equals(Integer.class) || TikTokDryRunVerdict.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((TikTokDryRunVerdict.class.equals(Float.class) || TikTokDryRunVerdict.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (TikTokDryRunVerdict.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (TikTokDryRunVerdict.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(TikTokDryRunVerdict.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'TikTokDryRunVerdict'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'TikTokDryRunVerdict'", e);
            }

            if (match == 1) {
                CreatePost200Response ret = new CreatePost200Response();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format(java.util.Locale.ROOT, "Failed deserialization for CreatePost200Response: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public CreatePost200Response getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "CreatePost200Response cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public CreatePost200Response() {
        super("oneOf", Boolean.FALSE);
    }

    public CreatePost200Response(PostCreateResponse o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public CreatePost200Response(TikTokDryRunVerdict o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("PostCreateResponse", PostCreateResponse.class);
        schemas.put("TikTokDryRunVerdict", TikTokDryRunVerdict.class);
        JSON.registerDescendants(CreatePost200Response.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return CreatePost200Response.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * PostCreateResponse, TikTokDryRunVerdict
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(PostCreateResponse.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(TikTokDryRunVerdict.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be PostCreateResponse, TikTokDryRunVerdict");
    }

    /**
     * Get the actual instance, which can be the following:
     * PostCreateResponse, TikTokDryRunVerdict
     *
     * @return The actual instance (PostCreateResponse, TikTokDryRunVerdict)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `PostCreateResponse`. If the actual instance is not `PostCreateResponse`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PostCreateResponse`
     * @throws ClassCastException if the instance is not `PostCreateResponse`
     */
    public PostCreateResponse getPostCreateResponse() throws ClassCastException {
        return (PostCreateResponse)super.getActualInstance();
    }

    /**
     * Get the actual instance of `TikTokDryRunVerdict`. If the actual instance is not `TikTokDryRunVerdict`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TikTokDryRunVerdict`
     * @throws ClassCastException if the instance is not `TikTokDryRunVerdict`
     */
    public TikTokDryRunVerdict getTikTokDryRunVerdict() throws ClassCastException {
        return (TikTokDryRunVerdict)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof TikTokDryRunVerdict) {
        if (getActualInstance() != null) {
          joiner.add(((TikTokDryRunVerdict)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof PostCreateResponse) {
        if (getActualInstance() != null) {
          joiner.add(((PostCreateResponse)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

