/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * CreateAdSetRequest
 */
@JsonPropertyOrder({
  CreateAdSetRequest.JSON_PROPERTY_ACCOUNT_ID,
  CreateAdSetRequest.JSON_PROPERTY_PLATFORM,
  CreateAdSetRequest.JSON_PROPERTY_CAMPAIGN_ID,
  CreateAdSetRequest.JSON_PROPERTY_NAME,
  CreateAdSetRequest.JSON_PROPERTY_STATUS,
  CreateAdSetRequest.JSON_PROPERTY_CUSTOMER_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-08T10:13:41.433058950Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class CreateAdSetRequest {
  public static final String JSON_PROPERTY_ACCOUNT_ID = "accountId";
  @javax.annotation.Nonnull
  private String accountId;

  /**
   * Only \&quot;google\&quot; is implemented today; every other value returns 501.
   */
  public enum PlatformEnum {
    FACEBOOK(String.valueOf("facebook")),
    
    INSTAGRAM(String.valueOf("instagram")),
    
    TIKTOK(String.valueOf("tiktok")),
    
    LINKEDIN(String.valueOf("linkedin")),
    
    PINTEREST(String.valueOf("pinterest")),
    
    GOOGLE(String.valueOf("google")),
    
    TWITTER(String.valueOf("twitter")),
    
    OPENAI(String.valueOf("openai"));

    private String value;

    PlatformEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PlatformEnum fromValue(String value) {
      for (PlatformEnum b : PlatformEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PLATFORM = "platform";
  @javax.annotation.Nonnull
  private PlatformEnum platform;

  public static final String JSON_PROPERTY_CAMPAIGN_ID = "campaignId";
  @javax.annotation.Nonnull
  private String campaignId;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    ACTIVE(String.valueOf("ACTIVE")),
    
    PAUSED(String.valueOf("PAUSED"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private StatusEnum status = StatusEnum.PAUSED;

  public static final String JSON_PROPERTY_CUSTOMER_ID = "customerId";
  @javax.annotation.Nullable
  private String customerId;

  public CreateAdSetRequest() { 
  }

  public CreateAdSetRequest accountId(@javax.annotation.Nonnull String accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Zernio SocialAccount id owning the Google Ads connection.
   * @return accountId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAccountId() {
    return accountId;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountId(@javax.annotation.Nonnull String accountId) {
    this.accountId = accountId;
  }


  public CreateAdSetRequest platform(@javax.annotation.Nonnull PlatformEnum platform) {
    this.platform = platform;
    return this;
  }

  /**
   * Only \&quot;google\&quot; is implemented today; every other value returns 501.
   * @return platform
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PLATFORM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PlatformEnum getPlatform() {
    return platform;
  }


  @JsonProperty(value = JSON_PROPERTY_PLATFORM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPlatform(@javax.annotation.Nonnull PlatformEnum platform) {
    this.platform = platform;
  }


  public CreateAdSetRequest campaignId(@javax.annotation.Nonnull String campaignId) {
    this.campaignId = campaignId;
    return this;
  }

  /**
   * Google platform campaign ID (numeric) the ad group is created under.
   * @return campaignId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CAMPAIGN_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCampaignId() {
    return campaignId;
  }


  @JsonProperty(value = JSON_PROPERTY_CAMPAIGN_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCampaignId(@javax.annotation.Nonnull String campaignId) {
    this.campaignId = campaignId;
  }


  public CreateAdSetRequest name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public CreateAdSetRequest status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public CreateAdSetRequest customerId(@javax.annotation.Nullable String customerId) {
    this.customerId = customerId;
    return this;
  }

  /**
   * Numeric Google Ads customer id. Only required when the connection has more than one.
   * @return customerId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCustomerId() {
    return customerId;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomerId(@javax.annotation.Nullable String customerId) {
    this.customerId = customerId;
  }


  /**
   * Return true if this createAdSet_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateAdSetRequest createAdSetRequest = (CreateAdSetRequest) o;
    return Objects.equals(this.accountId, createAdSetRequest.accountId) &&
        Objects.equals(this.platform, createAdSetRequest.platform) &&
        Objects.equals(this.campaignId, createAdSetRequest.campaignId) &&
        Objects.equals(this.name, createAdSetRequest.name) &&
        Objects.equals(this.status, createAdSetRequest.status) &&
        Objects.equals(this.customerId, createAdSetRequest.customerId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, platform, campaignId, name, status, customerId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateAdSetRequest {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    campaignId: ").append(toIndentedString(campaignId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `accountId` to the URL query string
    if (getAccountId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saccountId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAccountId()))));
    }

    // add `platform` to the URL query string
    if (getPlatform() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%splatform%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPlatform()))));
    }

    // add `campaignId` to the URL query string
    if (getCampaignId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scampaignId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCampaignId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `customerId` to the URL query string
    if (getCustomerId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scustomerId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCustomerId()))));
    }

    return joiner.toString();
  }
}

