/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.239.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * GetAnalyticsDashboard200ResponseDailyInner
 */
@JsonPropertyOrder({
  GetAnalyticsDashboard200ResponseDailyInner.JSON_PROPERTY_DATE,
  GetAnalyticsDashboard200ResponseDailyInner.JSON_PROPERTY_IMPRESSIONS,
  GetAnalyticsDashboard200ResponseDailyInner.JSON_PROPERTY_REACH,
  GetAnalyticsDashboard200ResponseDailyInner.JSON_PROPERTY_ENGAGEMENT,
  GetAnalyticsDashboard200ResponseDailyInner.JSON_PROPERTY_VIEWS,
  GetAnalyticsDashboard200ResponseDailyInner.JSON_PROPERTY_FOLLOWERS_GAINED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-10-07T20:29:04.823830096Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class GetAnalyticsDashboard200ResponseDailyInner {
  public static final String JSON_PROPERTY_DATE = "date";
  @javax.annotation.Nullable
  private LocalDate date;

  public static final String JSON_PROPERTY_IMPRESSIONS = "impressions";
  @javax.annotation.Nullable
  private Integer impressions;

  public static final String JSON_PROPERTY_REACH = "reach";
  @javax.annotation.Nullable
  private Integer reach;

  public static final String JSON_PROPERTY_ENGAGEMENT = "engagement";
  @javax.annotation.Nullable
  private Integer engagement;

  public static final String JSON_PROPERTY_VIEWS = "views";
  @javax.annotation.Nullable
  private Integer views;

  public static final String JSON_PROPERTY_FOLLOWERS_GAINED = "followersGained";
  @javax.annotation.Nullable
  private Integer followersGained;

  public GetAnalyticsDashboard200ResponseDailyInner() { 
  }

  public GetAnalyticsDashboard200ResponseDailyInner date(@javax.annotation.Nullable LocalDate date) {
    this.date = date;
    return this;
  }

  /**
   * Get date
   * @return date
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public LocalDate getDate() {
    return date;
  }


  @JsonProperty(value = JSON_PROPERTY_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDate(@javax.annotation.Nullable LocalDate date) {
    this.date = date;
  }


  public GetAnalyticsDashboard200ResponseDailyInner impressions(@javax.annotation.Nullable Integer impressions) {
    this.impressions = impressions;
    return this;
  }

  /**
   * Get impressions
   * @return impressions
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IMPRESSIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getImpressions() {
    return impressions;
  }


  @JsonProperty(value = JSON_PROPERTY_IMPRESSIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImpressions(@javax.annotation.Nullable Integer impressions) {
    this.impressions = impressions;
  }


  public GetAnalyticsDashboard200ResponseDailyInner reach(@javax.annotation.Nullable Integer reach) {
    this.reach = reach;
    return this;
  }

  /**
   * Get reach
   * @return reach
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REACH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getReach() {
    return reach;
  }


  @JsonProperty(value = JSON_PROPERTY_REACH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReach(@javax.annotation.Nullable Integer reach) {
    this.reach = reach;
  }


  public GetAnalyticsDashboard200ResponseDailyInner engagement(@javax.annotation.Nullable Integer engagement) {
    this.engagement = engagement;
    return this;
  }

  /**
   * Likes, comments, shares and saves received that day.
   * @return engagement
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENGAGEMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getEngagement() {
    return engagement;
  }


  @JsonProperty(value = JSON_PROPERTY_ENGAGEMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEngagement(@javax.annotation.Nullable Integer engagement) {
    this.engagement = engagement;
  }


  public GetAnalyticsDashboard200ResponseDailyInner views(@javax.annotation.Nullable Integer views) {
    this.views = views;
    return this;
  }

  /**
   * Get views
   * @return views
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VIEWS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getViews() {
    return views;
  }


  @JsonProperty(value = JSON_PROPERTY_VIEWS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setViews(@javax.annotation.Nullable Integer views) {
    this.views = views;
  }


  public GetAnalyticsDashboard200ResponseDailyInner followersGained(@javax.annotation.Nullable Integer followersGained) {
    this.followersGained = followersGained;
    return this;
  }

  /**
   * Net follower change against the previous snapshot. Can be negative.
   * @return followersGained
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FOLLOWERS_GAINED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getFollowersGained() {
    return followersGained;
  }


  @JsonProperty(value = JSON_PROPERTY_FOLLOWERS_GAINED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFollowersGained(@javax.annotation.Nullable Integer followersGained) {
    this.followersGained = followersGained;
  }


  /**
   * Return true if this getAnalyticsDashboard_200_response_daily_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAnalyticsDashboard200ResponseDailyInner getAnalyticsDashboard200ResponseDailyInner = (GetAnalyticsDashboard200ResponseDailyInner) o;
    return Objects.equals(this.date, getAnalyticsDashboard200ResponseDailyInner.date) &&
        Objects.equals(this.impressions, getAnalyticsDashboard200ResponseDailyInner.impressions) &&
        Objects.equals(this.reach, getAnalyticsDashboard200ResponseDailyInner.reach) &&
        Objects.equals(this.engagement, getAnalyticsDashboard200ResponseDailyInner.engagement) &&
        Objects.equals(this.views, getAnalyticsDashboard200ResponseDailyInner.views) &&
        Objects.equals(this.followersGained, getAnalyticsDashboard200ResponseDailyInner.followersGained);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, impressions, reach, engagement, views, followersGained);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAnalyticsDashboard200ResponseDailyInner {\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    impressions: ").append(toIndentedString(impressions)).append("\n");
    sb.append("    reach: ").append(toIndentedString(reach)).append("\n");
    sb.append("    engagement: ").append(toIndentedString(engagement)).append("\n");
    sb.append("    views: ").append(toIndentedString(views)).append("\n");
    sb.append("    followersGained: ").append(toIndentedString(followersGained)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `date` to the URL query string
    if (getDate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDate()))));
    }

    // add `impressions` to the URL query string
    if (getImpressions() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%simpressions%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getImpressions()))));
    }

    // add `reach` to the URL query string
    if (getReach() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreach%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReach()))));
    }

    // add `engagement` to the URL query string
    if (getEngagement() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sengagement%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEngagement()))));
    }

    // add `views` to the URL query string
    if (getViews() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sviews%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getViews()))));
    }

    // add `followersGained` to the URL query string
    if (getFollowersGained() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfollowersGained%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFollowersGained()))));
    }

    return joiner.toString();
  }
}

