/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.220.4
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * GetFacebookDemographics200ResponseDemographicsCountryInner
 */
@JsonPropertyOrder({
  GetFacebookDemographics200ResponseDemographicsCountryInner.JSON_PROPERTY_DIMENSION,
  GetFacebookDemographics200ResponseDemographicsCountryInner.JSON_PROPERTY_VALUE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-10-06T13:56:59.765601735Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class GetFacebookDemographics200ResponseDemographicsCountryInner {
  public static final String JSON_PROPERTY_DIMENSION = "dimension";
  @javax.annotation.Nullable
  private String dimension;

  public static final String JSON_PROPERTY_VALUE = "value";
  @javax.annotation.Nullable
  private Integer value;

  public GetFacebookDemographics200ResponseDemographicsCountryInner() { 
  }

  public GetFacebookDemographics200ResponseDemographicsCountryInner dimension(@javax.annotation.Nullable String dimension) {
    this.dimension = dimension;
    return this;
  }

  /**
   * Get dimension
   * @return dimension
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DIMENSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDimension() {
    return dimension;
  }


  @JsonProperty(value = JSON_PROPERTY_DIMENSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDimension(@javax.annotation.Nullable String dimension) {
    this.dimension = dimension;
  }


  public GetFacebookDemographics200ResponseDemographicsCountryInner value(@javax.annotation.Nullable Integer value) {
    this.value = value;
    return this;
  }

  /**
   * Followers
   * @return value
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getValue() {
    return value;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(@javax.annotation.Nullable Integer value) {
    this.value = value;
  }


  /**
   * Return true if this getFacebookDemographics_200_response_demographics_country_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetFacebookDemographics200ResponseDemographicsCountryInner getFacebookDemographics200ResponseDemographicsCountryInner = (GetFacebookDemographics200ResponseDemographicsCountryInner) o;
    return Objects.equals(this.dimension, getFacebookDemographics200ResponseDemographicsCountryInner.dimension) &&
        Objects.equals(this.value, getFacebookDemographics200ResponseDemographicsCountryInner.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dimension, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetFacebookDemographics200ResponseDemographicsCountryInner {\n");
    sb.append("    dimension: ").append(toIndentedString(dimension)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `dimension` to the URL query string
    if (getDimension() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdimension%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDimension()))));
    }

    // add `value` to the URL query string
    if (getValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svalue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getValue()))));
    }

    return joiner.toString();
  }
}

