/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInnerStartDate;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner
 */
@JsonPropertyOrder({
  GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner.JSON_PROPERTY_START_DATE,
  GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner.JSON_PROPERTY_END_DATE,
  GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner.JSON_PROPERTY_OPEN_TIME,
  GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner.JSON_PROPERTY_CLOSE_TIME,
  GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner.JSON_PROPERTY_CLOSED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-10T10:25:18.393151626Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner {
  public static final String JSON_PROPERTY_START_DATE = "startDate";
  @javax.annotation.Nullable
  private GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInnerStartDate startDate;

  public static final String JSON_PROPERTY_END_DATE = "endDate";
  @javax.annotation.Nullable
  private GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInnerStartDate endDate;

  public static final String JSON_PROPERTY_OPEN_TIME = "openTime";
  @javax.annotation.Nullable
  private String openTime;

  public static final String JSON_PROPERTY_CLOSE_TIME = "closeTime";
  @javax.annotation.Nullable
  private String closeTime;

  public static final String JSON_PROPERTY_CLOSED = "closed";
  @javax.annotation.Nullable
  private Boolean closed;

  public GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner() { 
  }

  public GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner startDate(@javax.annotation.Nullable GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInnerStartDate startDate) {
    this.startDate = startDate;
    return this;
  }

  /**
   * Get startDate
   * @return startDate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInnerStartDate getStartDate() {
    return startDate;
  }


  @JsonProperty(value = JSON_PROPERTY_START_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartDate(@javax.annotation.Nullable GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInnerStartDate startDate) {
    this.startDate = startDate;
  }


  public GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner endDate(@javax.annotation.Nullable GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInnerStartDate endDate) {
    this.endDate = endDate;
    return this;
  }

  /**
   * Get endDate
   * @return endDate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_END_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInnerStartDate getEndDate() {
    return endDate;
  }


  @JsonProperty(value = JSON_PROPERTY_END_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndDate(@javax.annotation.Nullable GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInnerStartDate endDate) {
    this.endDate = endDate;
  }


  public GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner openTime(@javax.annotation.Nullable String openTime) {
    this.openTime = openTime;
    return this;
  }

  /**
   * Get openTime
   * @return openTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPEN_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOpenTime() {
    return openTime;
  }


  @JsonProperty(value = JSON_PROPERTY_OPEN_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpenTime(@javax.annotation.Nullable String openTime) {
    this.openTime = openTime;
  }


  public GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner closeTime(@javax.annotation.Nullable String closeTime) {
    this.closeTime = closeTime;
    return this;
  }

  /**
   * Get closeTime
   * @return closeTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLOSE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCloseTime() {
    return closeTime;
  }


  @JsonProperty(value = JSON_PROPERTY_CLOSE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCloseTime(@javax.annotation.Nullable String closeTime) {
    this.closeTime = closeTime;
  }


  public GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner closed(@javax.annotation.Nullable Boolean closed) {
    this.closed = closed;
    return this;
  }

  /**
   * Get closed
   * @return closed
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLOSED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getClosed() {
    return closed;
  }


  @JsonProperty(value = JSON_PROPERTY_CLOSED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClosed(@javax.annotation.Nullable Boolean closed) {
    this.closed = closed;
  }


  /**
   * Return true if this getGoogleBusinessLocationDetails_200_response_specialHours_specialHourPeriods_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner getGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner = (GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner) o;
    return Objects.equals(this.startDate, getGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner.startDate) &&
        Objects.equals(this.endDate, getGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner.endDate) &&
        Objects.equals(this.openTime, getGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner.openTime) &&
        Objects.equals(this.closeTime, getGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner.closeTime) &&
        Objects.equals(this.closed, getGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner.closed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startDate, endDate, openTime, closeTime, closed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner {\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    openTime: ").append(toIndentedString(openTime)).append("\n");
    sb.append("    closeTime: ").append(toIndentedString(closeTime)).append("\n");
    sb.append("    closed: ").append(toIndentedString(closed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `startDate` to the URL query string
    if (getStartDate() != null) {
      joiner.add(getStartDate().toUrlQueryString(prefix + "startDate" + suffix));
    }

    // add `endDate` to the URL query string
    if (getEndDate() != null) {
      joiner.add(getEndDate().toUrlQueryString(prefix + "endDate" + suffix));
    }

    // add `openTime` to the URL query string
    if (getOpenTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sopenTime%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOpenTime()))));
    }

    // add `closeTime` to the URL query string
    if (getCloseTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scloseTime%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCloseTime()))));
    }

    // add `closed` to the URL query string
    if (getClosed() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sclosed%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getClosed()))));
    }

    return joiner.toString();
  }
}

