/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner
 */
@JsonPropertyOrder({
  GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner.JSON_PROPERTY_REQUIREMENT_ID,
  GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner.JSON_PROPERTY_LABEL,
  GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner.JSON_PROPERTY_KIND,
  GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner.JSON_PROPERTY_DESCRIPTION,
  GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner.JSON_PROPERTY_EXAMPLE,
  GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner.JSON_PROPERTY_ACCEPTABLE_VALUES,
  GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner.JSON_PROPERTY_STATUS,
  GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner.JSON_PROPERTY_FILLED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-24T14:22:12.290545658Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner {
  public static final String JSON_PROPERTY_REQUIREMENT_ID = "requirementId";
  @javax.annotation.Nullable
  private String requirementId;

  public static final String JSON_PROPERTY_LABEL = "label";
  @javax.annotation.Nullable
  private String label;

  /**
   * Gets or Sets kind
   */
  public enum KindEnum {
    TEXT(String.valueOf("text")),
    
    DATE(String.valueOf("date")),
    
    ADDRESS(String.valueOf("address")),
    
    FILE(String.valueOf("file")),
    
    ACTION(String.valueOf("action"));

    private String value;

    KindEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static KindEnum fromValue(String value) {
      for (KindEnum b : KindEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_KIND = "kind";
  @javax.annotation.Nullable
  private KindEnum kind;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_EXAMPLE = "example";
  @javax.annotation.Nullable
  private String example;

  public static final String JSON_PROPERTY_ACCEPTABLE_VALUES = "acceptableValues";
  @javax.annotation.Nullable
  private List<String> acceptableValues = new ArrayList<>();

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_FILLED = "filled";
  @javax.annotation.Nullable
  private Boolean filled;

  public GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner() { 
  }

  public GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner requirementId(@javax.annotation.Nullable String requirementId) {
    this.requirementId = requirementId;
    return this;
  }

  /**
   * Get requirementId
   * @return requirementId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REQUIREMENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRequirementId() {
    return requirementId;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUIREMENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequirementId(@javax.annotation.Nullable String requirementId) {
    this.requirementId = requirementId;
  }


  public GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner label(@javax.annotation.Nullable String label) {
    this.label = label;
    return this;
  }

  /**
   * Get label
   * @return label
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LABEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLabel() {
    return label;
  }


  @JsonProperty(value = JSON_PROPERTY_LABEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLabel(@javax.annotation.Nullable String label) {
    this.label = label;
  }


  public GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner kind(@javax.annotation.Nullable KindEnum kind) {
    this.kind = kind;
    return this;
  }

  /**
   * Get kind
   * @return kind
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KIND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public KindEnum getKind() {
    return kind;
  }


  @JsonProperty(value = JSON_PROPERTY_KIND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKind(@javax.annotation.Nullable KindEnum kind) {
    this.kind = kind;
  }


  public GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner example(@javax.annotation.Nullable String example) {
    this.example = example;
    return this;
  }

  /**
   * Get example
   * @return example
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXAMPLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getExample() {
    return example;
  }


  @JsonProperty(value = JSON_PROPERTY_EXAMPLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExample(@javax.annotation.Nullable String example) {
    this.example = example;
  }


  public GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner acceptableValues(@javax.annotation.Nullable List<String> acceptableValues) {
    this.acceptableValues = acceptableValues;
    return this;
  }

  public GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner addAcceptableValuesItem(String acceptableValuesItem) {
    if (this.acceptableValues == null) {
      this.acceptableValues = new ArrayList<>();
    }
    this.acceptableValues.add(acceptableValuesItem);
    return this;
  }

  /**
   * Get acceptableValues
   * @return acceptableValues
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACCEPTABLE_VALUES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getAcceptableValues() {
    return acceptableValues;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCEPTABLE_VALUES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAcceptableValues(@javax.annotation.Nullable List<String> acceptableValues) {
    this.acceptableValues = acceptableValues;
  }


  public GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * requirement-info-pending | requirement-info-under-review | requirement-info-exception | approved
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner filled(@javax.annotation.Nullable Boolean filled) {
    this.filled = filled;
    return this;
  }

  /**
   * Get filled
   * @return filled
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getFilled() {
    return filled;
  }


  @JsonProperty(value = JSON_PROPERTY_FILLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilled(@javax.annotation.Nullable Boolean filled) {
    this.filled = filled;
  }


  /**
   * Return true if this getPhoneNumberPortInOrderRequirements_200_response_requirements_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner getPhoneNumberPortInOrderRequirements200ResponseRequirementsInner = (GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner) o;
    return Objects.equals(this.requirementId, getPhoneNumberPortInOrderRequirements200ResponseRequirementsInner.requirementId) &&
        Objects.equals(this.label, getPhoneNumberPortInOrderRequirements200ResponseRequirementsInner.label) &&
        Objects.equals(this.kind, getPhoneNumberPortInOrderRequirements200ResponseRequirementsInner.kind) &&
        Objects.equals(this.description, getPhoneNumberPortInOrderRequirements200ResponseRequirementsInner.description) &&
        Objects.equals(this.example, getPhoneNumberPortInOrderRequirements200ResponseRequirementsInner.example) &&
        Objects.equals(this.acceptableValues, getPhoneNumberPortInOrderRequirements200ResponseRequirementsInner.acceptableValues) &&
        Objects.equals(this.status, getPhoneNumberPortInOrderRequirements200ResponseRequirementsInner.status) &&
        Objects.equals(this.filled, getPhoneNumberPortInOrderRequirements200ResponseRequirementsInner.filled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requirementId, label, kind, description, example, acceptableValues, status, filled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPhoneNumberPortInOrderRequirements200ResponseRequirementsInner {\n");
    sb.append("    requirementId: ").append(toIndentedString(requirementId)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    example: ").append(toIndentedString(example)).append("\n");
    sb.append("    acceptableValues: ").append(toIndentedString(acceptableValues)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    filled: ").append(toIndentedString(filled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `requirementId` to the URL query string
    if (getRequirementId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srequirementId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequirementId()))));
    }

    // add `label` to the URL query string
    if (getLabel() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slabel%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLabel()))));
    }

    // add `kind` to the URL query string
    if (getKind() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skind%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKind()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `example` to the URL query string
    if (getExample() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexample%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExample()))));
    }

    // add `acceptableValues` to the URL query string
    if (getAcceptableValues() != null) {
      for (int i = 0; i < getAcceptableValues().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sacceptableValues%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getAcceptableValues().get(i)))));
      }
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `filled` to the URL query string
    if (getFilled() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfilled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFilled()))));
    }

    return joiner.toString();
  }
}

