/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.229.0
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * InstagramBusinessDiscoveryProfile
 */
@JsonPropertyOrder({
  InstagramBusinessDiscoveryProfile.JSON_PROPERTY_ID,
  InstagramBusinessDiscoveryProfile.JSON_PROPERTY_USERNAME,
  InstagramBusinessDiscoveryProfile.JSON_PROPERTY_NAME,
  InstagramBusinessDiscoveryProfile.JSON_PROPERTY_BIOGRAPHY,
  InstagramBusinessDiscoveryProfile.JSON_PROPERTY_WEBSITE,
  InstagramBusinessDiscoveryProfile.JSON_PROPERTY_PROFILE_PICTURE_URL,
  InstagramBusinessDiscoveryProfile.JSON_PROPERTY_FOLLOWERS_COUNT,
  InstagramBusinessDiscoveryProfile.JSON_PROPERTY_FOLLOWS_COUNT,
  InstagramBusinessDiscoveryProfile.JSON_PROPERTY_MEDIA_COUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-10-07T07:44:11.352644149Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class InstagramBusinessDiscoveryProfile {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_USERNAME = "username";
  @javax.annotation.Nonnull
  private String username;

  public static final String JSON_PROPERTY_NAME = "name";
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_BIOGRAPHY = "biography";
  private JsonNullable<String> biography = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_WEBSITE = "website";
  private JsonNullable<String> website = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PROFILE_PICTURE_URL = "profilePictureUrl";
  private JsonNullable<String> profilePictureUrl = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_FOLLOWERS_COUNT = "followersCount";
  private JsonNullable<Integer> followersCount = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_FOLLOWS_COUNT = "followsCount";
  private JsonNullable<Integer> followsCount = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_MEDIA_COUNT = "mediaCount";
  private JsonNullable<Integer> mediaCount = JsonNullable.<Integer>undefined();

  public InstagramBusinessDiscoveryProfile() { 
  }

  public InstagramBusinessDiscoveryProfile id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Instagram user ID of the looked-up account
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public InstagramBusinessDiscoveryProfile username(@javax.annotation.Nonnull String username) {
    this.username = username;
    return this;
  }

  /**
   * Get username
   * @return username
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_USERNAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUsername() {
    return username;
  }


  @JsonProperty(value = JSON_PROPERTY_USERNAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUsername(@javax.annotation.Nonnull String username) {
    this.username = username;
  }


  public InstagramBusinessDiscoveryProfile name(@javax.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }


  public InstagramBusinessDiscoveryProfile biography(@javax.annotation.Nullable String biography) {
    this.biography = JsonNullable.<String>of(biography);
    return this;
  }

  /**
   * Get biography
   * @return biography
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getBiography() {
        return biography.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_BIOGRAPHY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getBiography_JsonNullable() {
    return biography;
  }
  
  @JsonProperty(JSON_PROPERTY_BIOGRAPHY)
  public void setBiography_JsonNullable(JsonNullable<String> biography) {
    this.biography = biography;
  }

  public void setBiography(@javax.annotation.Nullable String biography) {
    this.biography = JsonNullable.<String>of(biography);
  }


  public InstagramBusinessDiscoveryProfile website(@javax.annotation.Nullable String website) {
    this.website = JsonNullable.<String>of(website);
    return this;
  }

  /**
   * Get website
   * @return website
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getWebsite() {
        return website.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_WEBSITE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getWebsite_JsonNullable() {
    return website;
  }
  
  @JsonProperty(JSON_PROPERTY_WEBSITE)
  public void setWebsite_JsonNullable(JsonNullable<String> website) {
    this.website = website;
  }

  public void setWebsite(@javax.annotation.Nullable String website) {
    this.website = JsonNullable.<String>of(website);
  }


  public InstagramBusinessDiscoveryProfile profilePictureUrl(@javax.annotation.Nullable String profilePictureUrl) {
    this.profilePictureUrl = JsonNullable.<String>of(profilePictureUrl);
    return this;
  }

  /**
   * Temporary CDN URL; download it rather than storing the link.
   * @return profilePictureUrl
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getProfilePictureUrl() {
        return profilePictureUrl.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PROFILE_PICTURE_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getProfilePictureUrl_JsonNullable() {
    return profilePictureUrl;
  }
  
  @JsonProperty(JSON_PROPERTY_PROFILE_PICTURE_URL)
  public void setProfilePictureUrl_JsonNullable(JsonNullable<String> profilePictureUrl) {
    this.profilePictureUrl = profilePictureUrl;
  }

  public void setProfilePictureUrl(@javax.annotation.Nullable String profilePictureUrl) {
    this.profilePictureUrl = JsonNullable.<String>of(profilePictureUrl);
  }


  public InstagramBusinessDiscoveryProfile followersCount(@javax.annotation.Nullable Integer followersCount) {
    this.followersCount = JsonNullable.<Integer>of(followersCount);
    return this;
  }

  /**
   * Get followersCount
   * @return followersCount
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Integer getFollowersCount() {
        return followersCount.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_FOLLOWERS_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getFollowersCount_JsonNullable() {
    return followersCount;
  }
  
  @JsonProperty(JSON_PROPERTY_FOLLOWERS_COUNT)
  public void setFollowersCount_JsonNullable(JsonNullable<Integer> followersCount) {
    this.followersCount = followersCount;
  }

  public void setFollowersCount(@javax.annotation.Nullable Integer followersCount) {
    this.followersCount = JsonNullable.<Integer>of(followersCount);
  }


  public InstagramBusinessDiscoveryProfile followsCount(@javax.annotation.Nullable Integer followsCount) {
    this.followsCount = JsonNullable.<Integer>of(followsCount);
    return this;
  }

  /**
   * Get followsCount
   * @return followsCount
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Integer getFollowsCount() {
        return followsCount.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_FOLLOWS_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getFollowsCount_JsonNullable() {
    return followsCount;
  }
  
  @JsonProperty(JSON_PROPERTY_FOLLOWS_COUNT)
  public void setFollowsCount_JsonNullable(JsonNullable<Integer> followsCount) {
    this.followsCount = followsCount;
  }

  public void setFollowsCount(@javax.annotation.Nullable Integer followsCount) {
    this.followsCount = JsonNullable.<Integer>of(followsCount);
  }


  public InstagramBusinessDiscoveryProfile mediaCount(@javax.annotation.Nullable Integer mediaCount) {
    this.mediaCount = JsonNullable.<Integer>of(mediaCount);
    return this;
  }

  /**
   * Get mediaCount
   * @return mediaCount
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Integer getMediaCount() {
        return mediaCount.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_MEDIA_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getMediaCount_JsonNullable() {
    return mediaCount;
  }
  
  @JsonProperty(JSON_PROPERTY_MEDIA_COUNT)
  public void setMediaCount_JsonNullable(JsonNullable<Integer> mediaCount) {
    this.mediaCount = mediaCount;
  }

  public void setMediaCount(@javax.annotation.Nullable Integer mediaCount) {
    this.mediaCount = JsonNullable.<Integer>of(mediaCount);
  }


  /**
   * Return true if this InstagramBusinessDiscovery_profile object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstagramBusinessDiscoveryProfile instagramBusinessDiscoveryProfile = (InstagramBusinessDiscoveryProfile) o;
    return Objects.equals(this.id, instagramBusinessDiscoveryProfile.id) &&
        Objects.equals(this.username, instagramBusinessDiscoveryProfile.username) &&
        equalsNullable(this.name, instagramBusinessDiscoveryProfile.name) &&
        equalsNullable(this.biography, instagramBusinessDiscoveryProfile.biography) &&
        equalsNullable(this.website, instagramBusinessDiscoveryProfile.website) &&
        equalsNullable(this.profilePictureUrl, instagramBusinessDiscoveryProfile.profilePictureUrl) &&
        equalsNullable(this.followersCount, instagramBusinessDiscoveryProfile.followersCount) &&
        equalsNullable(this.followsCount, instagramBusinessDiscoveryProfile.followsCount) &&
        equalsNullable(this.mediaCount, instagramBusinessDiscoveryProfile.mediaCount);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, username, hashCodeNullable(name), hashCodeNullable(biography), hashCodeNullable(website), hashCodeNullable(profilePictureUrl), hashCodeNullable(followersCount), hashCodeNullable(followsCount), hashCodeNullable(mediaCount));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstagramBusinessDiscoveryProfile {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    biography: ").append(toIndentedString(biography)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    profilePictureUrl: ").append(toIndentedString(profilePictureUrl)).append("\n");
    sb.append("    followersCount: ").append(toIndentedString(followersCount)).append("\n");
    sb.append("    followsCount: ").append(toIndentedString(followsCount)).append("\n");
    sb.append("    mediaCount: ").append(toIndentedString(mediaCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `username` to the URL query string
    if (getUsername() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%susername%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUsername()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `biography` to the URL query string
    if (getBiography() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbiography%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBiography()))));
    }

    // add `website` to the URL query string
    if (getWebsite() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swebsite%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWebsite()))));
    }

    // add `profilePictureUrl` to the URL query string
    if (getProfilePictureUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprofilePictureUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProfilePictureUrl()))));
    }

    // add `followersCount` to the URL query string
    if (getFollowersCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfollowersCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFollowersCount()))));
    }

    // add `followsCount` to the URL query string
    if (getFollowsCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfollowsCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFollowsCount()))));
    }

    // add `mediaCount` to the URL query string
    if (getMediaCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smediaCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMediaCount()))));
    }

    return joiner.toString();
  }
}

