/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * LinkedInAdsPlatformDataConversationMessagesInnerButtonsInner
 */
@JsonPropertyOrder({
  LinkedInAdsPlatformDataConversationMessagesInnerButtonsInner.JSON_PROPERTY_TEXT,
  LinkedInAdsPlatformDataConversationMessagesInnerButtonsInner.JSON_PROPERTY_NEXT_MESSAGE_ID,
  LinkedInAdsPlatformDataConversationMessagesInnerButtonsInner.JSON_PROPERTY_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-22T11:59:21.037552865Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class LinkedInAdsPlatformDataConversationMessagesInnerButtonsInner {
  public static final String JSON_PROPERTY_TEXT = "text";
  @javax.annotation.Nonnull
  private String text;

  public static final String JSON_PROPERTY_NEXT_MESSAGE_ID = "nextMessageId";
  @javax.annotation.Nullable
  private String nextMessageId;

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nullable
  private URI url;

  public LinkedInAdsPlatformDataConversationMessagesInnerButtonsInner() { 
  }

  public LinkedInAdsPlatformDataConversationMessagesInnerButtonsInner text(@javax.annotation.Nonnull String text) {
    this.text = text;
    return this;
  }

  /**
   * Get text
   * @return text
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TEXT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getText() {
    return text;
  }


  @JsonProperty(value = JSON_PROPERTY_TEXT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setText(@javax.annotation.Nonnull String text) {
    this.text = text;
  }


  public LinkedInAdsPlatformDataConversationMessagesInnerButtonsInner nextMessageId(@javax.annotation.Nullable String nextMessageId) {
    this.nextMessageId = nextMessageId;
    return this;
  }

  /**
   * Continues the conversation at this message. Exactly one of nextMessageId or url.
   * @return nextMessageId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NEXT_MESSAGE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNextMessageId() {
    return nextMessageId;
  }


  @JsonProperty(value = JSON_PROPERTY_NEXT_MESSAGE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextMessageId(@javax.annotation.Nullable String nextMessageId) {
    this.nextMessageId = nextMessageId;
  }


  public LinkedInAdsPlatformDataConversationMessagesInnerButtonsInner url(@javax.annotation.Nullable URI url) {
    this.url = url;
    return this;
  }

  /**
   * Opens this landing page. Exactly one of nextMessageId or url.
   * @return url
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getUrl() {
    return url;
  }


  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@javax.annotation.Nullable URI url) {
    this.url = url;
  }


  /**
   * Return true if this LinkedInAdsPlatformData_conversation_messages_inner_buttons_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkedInAdsPlatformDataConversationMessagesInnerButtonsInner linkedInAdsPlatformDataConversationMessagesInnerButtonsInner = (LinkedInAdsPlatformDataConversationMessagesInnerButtonsInner) o;
    return Objects.equals(this.text, linkedInAdsPlatformDataConversationMessagesInnerButtonsInner.text) &&
        Objects.equals(this.nextMessageId, linkedInAdsPlatformDataConversationMessagesInnerButtonsInner.nextMessageId) &&
        Objects.equals(this.url, linkedInAdsPlatformDataConversationMessagesInnerButtonsInner.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, nextMessageId, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkedInAdsPlatformDataConversationMessagesInnerButtonsInner {\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    nextMessageId: ").append(toIndentedString(nextMessageId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `text` to the URL query string
    if (getText() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stext%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getText()))));
    }

    // add `nextMessageId` to the URL query string
    if (getNextMessageId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snextMessageId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNextMessageId()))));
    }

    // add `url` to the URL query string
    if (getUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%surl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUrl()))));
    }

    return joiner.toString();
  }
}

