/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * ListInboxComments200ResponseDataInner
 */
@JsonPropertyOrder({
  ListInboxComments200ResponseDataInner.JSON_PROPERTY_ID,
  ListInboxComments200ResponseDataInner.JSON_PROPERTY_PLATFORM,
  ListInboxComments200ResponseDataInner.JSON_PROPERTY_ACCOUNT_ID,
  ListInboxComments200ResponseDataInner.JSON_PROPERTY_ACCOUNT_USERNAME,
  ListInboxComments200ResponseDataInner.JSON_PROPERTY_CONTENT,
  ListInboxComments200ResponseDataInner.JSON_PROPERTY_PICTURE,
  ListInboxComments200ResponseDataInner.JSON_PROPERTY_PERMALINK,
  ListInboxComments200ResponseDataInner.JSON_PROPERTY_CREATED_TIME,
  ListInboxComments200ResponseDataInner.JSON_PROPERTY_COMMENT_COUNT,
  ListInboxComments200ResponseDataInner.JSON_PROPERTY_LIKE_COUNT,
  ListInboxComments200ResponseDataInner.JSON_PROPERTY_CID,
  ListInboxComments200ResponseDataInner.JSON_PROPERTY_SUBREDDIT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-14T11:43:39.105583357Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class ListInboxComments200ResponseDataInner {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_PLATFORM = "platform";
  @javax.annotation.Nullable
  private String platform;

  public static final String JSON_PROPERTY_ACCOUNT_ID = "accountId";
  @javax.annotation.Nullable
  private String accountId;

  public static final String JSON_PROPERTY_ACCOUNT_USERNAME = "accountUsername";
  @javax.annotation.Nullable
  private String accountUsername;

  public static final String JSON_PROPERTY_CONTENT = "content";
  @javax.annotation.Nullable
  private String content;

  public static final String JSON_PROPERTY_PICTURE = "picture";
  @javax.annotation.Nullable
  private String picture;

  public static final String JSON_PROPERTY_PERMALINK = "permalink";
  @javax.annotation.Nullable
  private String permalink;

  public static final String JSON_PROPERTY_CREATED_TIME = "createdTime";
  @javax.annotation.Nullable
  private OffsetDateTime createdTime;

  public static final String JSON_PROPERTY_COMMENT_COUNT = "commentCount";
  @javax.annotation.Nullable
  private Integer commentCount;

  public static final String JSON_PROPERTY_LIKE_COUNT = "likeCount";
  @javax.annotation.Nullable
  private Integer likeCount;

  public static final String JSON_PROPERTY_CID = "cid";
  @javax.annotation.Nullable
  private String cid;

  public static final String JSON_PROPERTY_SUBREDDIT = "subreddit";
  @javax.annotation.Nullable
  private String subreddit;

  public ListInboxComments200ResponseDataInner() { 
  }

  public ListInboxComments200ResponseDataInner id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public ListInboxComments200ResponseDataInner platform(@javax.annotation.Nullable String platform) {
    this.platform = platform;
    return this;
  }

  /**
   * Get platform
   * @return platform
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PLATFORM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPlatform() {
    return platform;
  }


  @JsonProperty(value = JSON_PROPERTY_PLATFORM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlatform(@javax.annotation.Nullable String platform) {
    this.platform = platform;
  }


  public ListInboxComments200ResponseDataInner accountId(@javax.annotation.Nullable String accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   * @return accountId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAccountId() {
    return accountId;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountId(@javax.annotation.Nullable String accountId) {
    this.accountId = accountId;
  }


  public ListInboxComments200ResponseDataInner accountUsername(@javax.annotation.Nullable String accountUsername) {
    this.accountUsername = accountUsername;
    return this;
  }

  /**
   * Get accountUsername
   * @return accountUsername
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_USERNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAccountUsername() {
    return accountUsername;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_USERNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountUsername(@javax.annotation.Nullable String accountUsername) {
    this.accountUsername = accountUsername;
  }


  public ListInboxComments200ResponseDataInner content(@javax.annotation.Nullable String content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContent(@javax.annotation.Nullable String content) {
    this.content = content;
  }


  public ListInboxComments200ResponseDataInner picture(@javax.annotation.Nullable String picture) {
    this.picture = picture;
    return this;
  }

  /**
   * Get picture
   * @return picture
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PICTURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPicture() {
    return picture;
  }


  @JsonProperty(value = JSON_PROPERTY_PICTURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPicture(@javax.annotation.Nullable String picture) {
    this.picture = picture;
  }


  public ListInboxComments200ResponseDataInner permalink(@javax.annotation.Nullable String permalink) {
    this.permalink = permalink;
    return this;
  }

  /**
   * Get permalink
   * @return permalink
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PERMALINK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPermalink() {
    return permalink;
  }


  @JsonProperty(value = JSON_PROPERTY_PERMALINK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPermalink(@javax.annotation.Nullable String permalink) {
    this.permalink = permalink;
  }


  public ListInboxComments200ResponseDataInner createdTime(@javax.annotation.Nullable OffsetDateTime createdTime) {
    this.createdTime = createdTime;
    return this;
  }

  /**
   * Get createdTime
   * @return createdTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedTime() {
    return createdTime;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedTime(@javax.annotation.Nullable OffsetDateTime createdTime) {
    this.createdTime = createdTime;
  }


  public ListInboxComments200ResponseDataInner commentCount(@javax.annotation.Nullable Integer commentCount) {
    this.commentCount = commentCount;
    return this;
  }

  /**
   * Get commentCount
   * @return commentCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMENT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getCommentCount() {
    return commentCount;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMENT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommentCount(@javax.annotation.Nullable Integer commentCount) {
    this.commentCount = commentCount;
  }


  public ListInboxComments200ResponseDataInner likeCount(@javax.annotation.Nullable Integer likeCount) {
    this.likeCount = likeCount;
    return this;
  }

  /**
   * Get likeCount
   * @return likeCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LIKE_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getLikeCount() {
    return likeCount;
  }


  @JsonProperty(value = JSON_PROPERTY_LIKE_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLikeCount(@javax.annotation.Nullable Integer likeCount) {
    this.likeCount = likeCount;
  }


  public ListInboxComments200ResponseDataInner cid(@javax.annotation.Nullable String cid) {
    this.cid = cid;
    return this;
  }

  /**
   * Bluesky content identifier
   * @return cid
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCid() {
    return cid;
  }


  @JsonProperty(value = JSON_PROPERTY_CID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCid(@javax.annotation.Nullable String cid) {
    this.cid = cid;
  }


  public ListInboxComments200ResponseDataInner subreddit(@javax.annotation.Nullable String subreddit) {
    this.subreddit = subreddit;
    return this;
  }

  /**
   * Reddit subreddit name
   * @return subreddit
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUBREDDIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSubreddit() {
    return subreddit;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBREDDIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubreddit(@javax.annotation.Nullable String subreddit) {
    this.subreddit = subreddit;
  }


  /**
   * Return true if this listInboxComments_200_response_data_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListInboxComments200ResponseDataInner listInboxComments200ResponseDataInner = (ListInboxComments200ResponseDataInner) o;
    return Objects.equals(this.id, listInboxComments200ResponseDataInner.id) &&
        Objects.equals(this.platform, listInboxComments200ResponseDataInner.platform) &&
        Objects.equals(this.accountId, listInboxComments200ResponseDataInner.accountId) &&
        Objects.equals(this.accountUsername, listInboxComments200ResponseDataInner.accountUsername) &&
        Objects.equals(this.content, listInboxComments200ResponseDataInner.content) &&
        Objects.equals(this.picture, listInboxComments200ResponseDataInner.picture) &&
        Objects.equals(this.permalink, listInboxComments200ResponseDataInner.permalink) &&
        Objects.equals(this.createdTime, listInboxComments200ResponseDataInner.createdTime) &&
        Objects.equals(this.commentCount, listInboxComments200ResponseDataInner.commentCount) &&
        Objects.equals(this.likeCount, listInboxComments200ResponseDataInner.likeCount) &&
        Objects.equals(this.cid, listInboxComments200ResponseDataInner.cid) &&
        Objects.equals(this.subreddit, listInboxComments200ResponseDataInner.subreddit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, platform, accountId, accountUsername, content, picture, permalink, createdTime, commentCount, likeCount, cid, subreddit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListInboxComments200ResponseDataInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    accountUsername: ").append(toIndentedString(accountUsername)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    picture: ").append(toIndentedString(picture)).append("\n");
    sb.append("    permalink: ").append(toIndentedString(permalink)).append("\n");
    sb.append("    createdTime: ").append(toIndentedString(createdTime)).append("\n");
    sb.append("    commentCount: ").append(toIndentedString(commentCount)).append("\n");
    sb.append("    likeCount: ").append(toIndentedString(likeCount)).append("\n");
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    subreddit: ").append(toIndentedString(subreddit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `platform` to the URL query string
    if (getPlatform() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%splatform%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPlatform()))));
    }

    // add `accountId` to the URL query string
    if (getAccountId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saccountId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAccountId()))));
    }

    // add `accountUsername` to the URL query string
    if (getAccountUsername() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saccountUsername%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAccountUsername()))));
    }

    // add `content` to the URL query string
    if (getContent() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scontent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContent()))));
    }

    // add `picture` to the URL query string
    if (getPicture() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spicture%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPicture()))));
    }

    // add `permalink` to the URL query string
    if (getPermalink() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spermalink%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPermalink()))));
    }

    // add `createdTime` to the URL query string
    if (getCreatedTime() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedTime%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedTime()))));
    }

    // add `commentCount` to the URL query string
    if (getCommentCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scommentCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCommentCount()))));
    }

    // add `likeCount` to the URL query string
    if (getLikeCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slikeCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLikeCount()))));
    }

    // add `cid` to the URL query string
    if (getCid() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCid()))));
    }

    // add `subreddit` to the URL query string
    if (getSubreddit() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubreddit%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubreddit()))));
    }

    return joiner.toString();
  }
}

