/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * ListWhatsAppConversions200ResponseEventsInner
 */
@JsonPropertyOrder({
  ListWhatsAppConversions200ResponseEventsInner.JSON_PROPERTY_TIMESTAMP,
  ListWhatsAppConversions200ResponseEventsInner.JSON_PROPERTY_EVENT_NAME,
  ListWhatsAppConversions200ResponseEventsInner.JSON_PROPERTY_CONVERSATION_ID,
  ListWhatsAppConversions200ResponseEventsInner.JSON_PROPERTY_EVENTS_RECEIVED,
  ListWhatsAppConversions200ResponseEventsInner.JSON_PROPERTY_EVENTS_FAILED,
  ListWhatsAppConversions200ResponseEventsInner.JSON_PROPERTY_TRACE_ID,
  ListWhatsAppConversions200ResponseEventsInner.JSON_PROPERTY_DURATION_MS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-09T13:24:42.414017337Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class ListWhatsAppConversions200ResponseEventsInner {
  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @javax.annotation.Nullable
  private OffsetDateTime timestamp;

  public static final String JSON_PROPERTY_EVENT_NAME = "eventName";
  @javax.annotation.Nullable
  private String eventName;

  public static final String JSON_PROPERTY_CONVERSATION_ID = "conversationId";
  @javax.annotation.Nullable
  private String conversationId;

  public static final String JSON_PROPERTY_EVENTS_RECEIVED = "eventsReceived";
  @javax.annotation.Nullable
  private Integer eventsReceived;

  public static final String JSON_PROPERTY_EVENTS_FAILED = "eventsFailed";
  @javax.annotation.Nullable
  private Integer eventsFailed;

  public static final String JSON_PROPERTY_TRACE_ID = "traceId";
  @javax.annotation.Nullable
  private String traceId;

  public static final String JSON_PROPERTY_DURATION_MS = "durationMs";
  @javax.annotation.Nullable
  private Integer durationMs;

  public ListWhatsAppConversions200ResponseEventsInner() { 
  }

  public ListWhatsAppConversions200ResponseEventsInner timestamp(@javax.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * When the event was sent to Meta.
   * @return timestamp
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@javax.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public ListWhatsAppConversions200ResponseEventsInner eventName(@javax.annotation.Nullable String eventName) {
    this.eventName = eventName;
    return this;
  }

  /**
   * One of LeadSubmitted, Purchase, AddToCart, InitiateCheckout, ViewContent.
   * @return eventName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EVENT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEventName() {
    return eventName;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventName(@javax.annotation.Nullable String eventName) {
    this.eventName = eventName;
  }


  public ListWhatsAppConversions200ResponseEventsInner conversationId(@javax.annotation.Nullable String conversationId) {
    this.conversationId = conversationId;
    return this;
  }

  /**
   * Get conversationId
   * @return conversationId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONVERSATION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getConversationId() {
    return conversationId;
  }


  @JsonProperty(value = JSON_PROPERTY_CONVERSATION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConversationId(@javax.annotation.Nullable String conversationId) {
    this.conversationId = conversationId;
  }


  public ListWhatsAppConversions200ResponseEventsInner eventsReceived(@javax.annotation.Nullable Integer eventsReceived) {
    this.eventsReceived = eventsReceived;
    return this;
  }

  /**
   * Number of events Meta accepted on this send (usually 1).
   * @return eventsReceived
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EVENTS_RECEIVED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getEventsReceived() {
    return eventsReceived;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENTS_RECEIVED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventsReceived(@javax.annotation.Nullable Integer eventsReceived) {
    this.eventsReceived = eventsReceived;
  }


  public ListWhatsAppConversions200ResponseEventsInner eventsFailed(@javax.annotation.Nullable Integer eventsFailed) {
    this.eventsFailed = eventsFailed;
    return this;
  }

  /**
   * Number of events Meta rejected (usually 0).
   * @return eventsFailed
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EVENTS_FAILED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getEventsFailed() {
    return eventsFailed;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENTS_FAILED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventsFailed(@javax.annotation.Nullable Integer eventsFailed) {
    this.eventsFailed = eventsFailed;
  }


  public ListWhatsAppConversions200ResponseEventsInner traceId(@javax.annotation.Nullable String traceId) {
    this.traceId = traceId;
    return this;
  }

  /**
   * Meta fbtrace_id for cross-referencing in Events Manager.
   * @return traceId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRACE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTraceId() {
    return traceId;
  }


  @JsonProperty(value = JSON_PROPERTY_TRACE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTraceId(@javax.annotation.Nullable String traceId) {
    this.traceId = traceId;
  }


  public ListWhatsAppConversions200ResponseEventsInner durationMs(@javax.annotation.Nullable Integer durationMs) {
    this.durationMs = durationMs;
    return this;
  }

  /**
   * Get durationMs
   * @return durationMs
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DURATION_MS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getDurationMs() {
    return durationMs;
  }


  @JsonProperty(value = JSON_PROPERTY_DURATION_MS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDurationMs(@javax.annotation.Nullable Integer durationMs) {
    this.durationMs = durationMs;
  }


  /**
   * Return true if this listWhatsAppConversions_200_response_events_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListWhatsAppConversions200ResponseEventsInner listWhatsAppConversions200ResponseEventsInner = (ListWhatsAppConversions200ResponseEventsInner) o;
    return Objects.equals(this.timestamp, listWhatsAppConversions200ResponseEventsInner.timestamp) &&
        Objects.equals(this.eventName, listWhatsAppConversions200ResponseEventsInner.eventName) &&
        Objects.equals(this.conversationId, listWhatsAppConversions200ResponseEventsInner.conversationId) &&
        Objects.equals(this.eventsReceived, listWhatsAppConversions200ResponseEventsInner.eventsReceived) &&
        Objects.equals(this.eventsFailed, listWhatsAppConversions200ResponseEventsInner.eventsFailed) &&
        Objects.equals(this.traceId, listWhatsAppConversions200ResponseEventsInner.traceId) &&
        Objects.equals(this.durationMs, listWhatsAppConversions200ResponseEventsInner.durationMs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, eventName, conversationId, eventsReceived, eventsFailed, traceId, durationMs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListWhatsAppConversions200ResponseEventsInner {\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    eventName: ").append(toIndentedString(eventName)).append("\n");
    sb.append("    conversationId: ").append(toIndentedString(conversationId)).append("\n");
    sb.append("    eventsReceived: ").append(toIndentedString(eventsReceived)).append("\n");
    sb.append("    eventsFailed: ").append(toIndentedString(eventsFailed)).append("\n");
    sb.append("    traceId: ").append(toIndentedString(traceId)).append("\n");
    sb.append("    durationMs: ").append(toIndentedString(durationMs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `timestamp` to the URL query string
    if (getTimestamp() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimestamp()))));
    }

    // add `eventName` to the URL query string
    if (getEventName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%seventName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEventName()))));
    }

    // add `conversationId` to the URL query string
    if (getConversationId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sconversationId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getConversationId()))));
    }

    // add `eventsReceived` to the URL query string
    if (getEventsReceived() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%seventsReceived%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEventsReceived()))));
    }

    // add `eventsFailed` to the URL query string
    if (getEventsFailed() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%seventsFailed%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEventsFailed()))));
    }

    // add `traceId` to the URL query string
    if (getTraceId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%straceId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTraceId()))));
    }

    // add `durationMs` to the URL query string
    if (getDurationMs() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdurationMs%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDurationMs()))));
    }

    return joiner.toString();
  }
}

