/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.ListContacts200ResponsePagination;
import dev.zernio.model.ListWorkflows200ResponseWorkflowsInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * ListWorkflows200Response
 */
@JsonPropertyOrder({
  ListWorkflows200Response.JSON_PROPERTY_SUCCESS,
  ListWorkflows200Response.JSON_PROPERTY_WORKFLOWS,
  ListWorkflows200Response.JSON_PROPERTY_PAGINATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-02T09:24:12.637229707Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class ListWorkflows200Response {
  public static final String JSON_PROPERTY_SUCCESS = "success";
  @javax.annotation.Nullable
  private Boolean success;

  public static final String JSON_PROPERTY_WORKFLOWS = "workflows";
  @javax.annotation.Nullable
  private List<ListWorkflows200ResponseWorkflowsInner> workflows = new ArrayList<>();

  public static final String JSON_PROPERTY_PAGINATION = "pagination";
  @javax.annotation.Nullable
  private ListContacts200ResponsePagination pagination;

  public ListWorkflows200Response() { 
  }

  public ListWorkflows200Response success(@javax.annotation.Nullable Boolean success) {
    this.success = success;
    return this;
  }

  /**
   * Get success
   * @return success
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUCCESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSuccess() {
    return success;
  }


  @JsonProperty(value = JSON_PROPERTY_SUCCESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuccess(@javax.annotation.Nullable Boolean success) {
    this.success = success;
  }


  public ListWorkflows200Response workflows(@javax.annotation.Nullable List<ListWorkflows200ResponseWorkflowsInner> workflows) {
    this.workflows = workflows;
    return this;
  }

  public ListWorkflows200Response addWorkflowsItem(ListWorkflows200ResponseWorkflowsInner workflowsItem) {
    if (this.workflows == null) {
      this.workflows = new ArrayList<>();
    }
    this.workflows.add(workflowsItem);
    return this;
  }

  /**
   * Get workflows
   * @return workflows
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WORKFLOWS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<ListWorkflows200ResponseWorkflowsInner> getWorkflows() {
    return workflows;
  }


  @JsonProperty(value = JSON_PROPERTY_WORKFLOWS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWorkflows(@javax.annotation.Nullable List<ListWorkflows200ResponseWorkflowsInner> workflows) {
    this.workflows = workflows;
  }


  public ListWorkflows200Response pagination(@javax.annotation.Nullable ListContacts200ResponsePagination pagination) {
    this.pagination = pagination;
    return this;
  }

  /**
   * Get pagination
   * @return pagination
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGINATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ListContacts200ResponsePagination getPagination() {
    return pagination;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGINATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPagination(@javax.annotation.Nullable ListContacts200ResponsePagination pagination) {
    this.pagination = pagination;
  }


  /**
   * Return true if this listWorkflows_200_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListWorkflows200Response listWorkflows200Response = (ListWorkflows200Response) o;
    return Objects.equals(this.success, listWorkflows200Response.success) &&
        Objects.equals(this.workflows, listWorkflows200Response.workflows) &&
        Objects.equals(this.pagination, listWorkflows200Response.pagination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(success, workflows, pagination);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListWorkflows200Response {\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    workflows: ").append(toIndentedString(workflows)).append("\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `success` to the URL query string
    if (getSuccess() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssuccess%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSuccess()))));
    }

    // add `workflows` to the URL query string
    if (getWorkflows() != null) {
      for (int i = 0; i < getWorkflows().size(); i++) {
        if (getWorkflows().get(i) != null) {
          joiner.add(getWorkflows().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sworkflows%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `pagination` to the URL query string
    if (getPagination() != null) {
      joiner.add(getPagination().toUrlQueryString(prefix + "pagination" + suffix));
    }

    return joiner.toString();
  }
}

