/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * ListAdAccounts200ResponseAccountsInner
 */
@JsonPropertyOrder({
  ListAdAccounts200ResponseAccountsInner.JSON_PROPERTY_ID,
  ListAdAccounts200ResponseAccountsInner.JSON_PROPERTY_NAME,
  ListAdAccounts200ResponseAccountsInner.JSON_PROPERTY_CURRENCY,
  ListAdAccounts200ResponseAccountsInner.JSON_PROPERTY_STATUS,
  ListAdAccounts200ResponseAccountsInner.JSON_PROPERTY_TIMEZONE_NAME,
  ListAdAccounts200ResponseAccountsInner.JSON_PROPERTY_TIMEZONE_OFFSET_HOURS_UTC
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-07T16:25:23.351483204Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class ListAdAccounts200ResponseAccountsInner {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nullable
  private String currency;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_TIMEZONE_NAME = "timezoneName";
  @javax.annotation.Nullable
  private String timezoneName;

  public static final String JSON_PROPERTY_TIMEZONE_OFFSET_HOURS_UTC = "timezoneOffsetHoursUtc";
  @javax.annotation.Nullable
  private BigDecimal timezoneOffsetHoursUtc;

  public ListAdAccounts200ResponseAccountsInner() { 
  }

  public ListAdAccounts200ResponseAccountsInner id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Platform ad account ID (e.g. act_123)
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public ListAdAccounts200ResponseAccountsInner name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public ListAdAccounts200ResponseAccountsInner currency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }


  public ListAdAccounts200ResponseAccountsInner status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public ListAdAccounts200ResponseAccountsInner timezoneName(@javax.annotation.Nullable String timezoneName) {
    this.timezoneName = timezoneName;
    return this;
  }

  /**
   * IANA timezone of the ad account (Meta only). Drives daily-budget reset and Insights day boundaries.
   * @return timezoneName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMEZONE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTimezoneName() {
    return timezoneName;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMEZONE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimezoneName(@javax.annotation.Nullable String timezoneName) {
    this.timezoneName = timezoneName;
  }


  public ListAdAccounts200ResponseAccountsInner timezoneOffsetHoursUtc(@javax.annotation.Nullable BigDecimal timezoneOffsetHoursUtc) {
    this.timezoneOffsetHoursUtc = timezoneOffsetHoursUtc;
    return this;
  }

  /**
   * Signed UTC offset in hours, reflecting current DST (Meta only).
   * @return timezoneOffsetHoursUtc
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMEZONE_OFFSET_HOURS_UTC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getTimezoneOffsetHoursUtc() {
    return timezoneOffsetHoursUtc;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMEZONE_OFFSET_HOURS_UTC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimezoneOffsetHoursUtc(@javax.annotation.Nullable BigDecimal timezoneOffsetHoursUtc) {
    this.timezoneOffsetHoursUtc = timezoneOffsetHoursUtc;
  }


  /**
   * Return true if this listAdAccounts_200_response_accounts_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListAdAccounts200ResponseAccountsInner listAdAccounts200ResponseAccountsInner = (ListAdAccounts200ResponseAccountsInner) o;
    return Objects.equals(this.id, listAdAccounts200ResponseAccountsInner.id) &&
        Objects.equals(this.name, listAdAccounts200ResponseAccountsInner.name) &&
        Objects.equals(this.currency, listAdAccounts200ResponseAccountsInner.currency) &&
        Objects.equals(this.status, listAdAccounts200ResponseAccountsInner.status) &&
        Objects.equals(this.timezoneName, listAdAccounts200ResponseAccountsInner.timezoneName) &&
        Objects.equals(this.timezoneOffsetHoursUtc, listAdAccounts200ResponseAccountsInner.timezoneOffsetHoursUtc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, currency, status, timezoneName, timezoneOffsetHoursUtc);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListAdAccounts200ResponseAccountsInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    timezoneName: ").append(toIndentedString(timezoneName)).append("\n");
    sb.append("    timezoneOffsetHoursUtc: ").append(toIndentedString(timezoneOffsetHoursUtc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `timezoneName` to the URL query string
    if (getTimezoneName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimezoneName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimezoneName()))));
    }

    // add `timezoneOffsetHoursUtc` to the URL query string
    if (getTimezoneOffsetHoursUtc() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimezoneOffsetHoursUtc%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimezoneOffsetHoursUtc()))));
    }

    return joiner.toString();
  }
}

