/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.98.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.ListSmsRegistrations200ResponseRegistrationsInnerThroughput;
import dev.zernio.model.SmsRegistrationReviewRequest;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * ListSmsRegistrations200ResponseRegistrationsInner
 */
@JsonPropertyOrder({
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_ID,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_REGISTRATION_TYPE,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_DISPLAY_NAME,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_STATUS,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_BRAND_STATUS,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_CAMPAIGN_STATUS,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_BRAND_ID,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_CAMPAIGN_ID,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_DECLINE_REASON,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_TF_ACTION_REQUIRED_AT,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_PHONE_NUMBERS,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_AWAITING_OTP,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_ADMIN_REVIEW_NOTE,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_LAST_RESPONSE_AT,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_PREVIOUSLY_REJECTED,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_LAST_REJECTED_AT,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_REJECTED_BEFORE_SUBMISSION,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_OTP_EXPIRED,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_REVIEW_REQUEST,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_TRUST_SCORE,
  ListSmsRegistrations200ResponseRegistrationsInner.JSON_PROPERTY_THROUGHPUT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-26T07:15:06.901284612Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class ListSmsRegistrations200ResponseRegistrationsInner {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  /**
   * Gets or Sets registrationType
   */
  public enum RegistrationTypeEnum {
    STANDARD_10DLC(String.valueOf("standard_10dlc")),
    
    SOLE_PROP_10DLC(String.valueOf("sole_prop_10dlc")),
    
    TOLL_FREE(String.valueOf("toll_free"));

    private String value;

    RegistrationTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RegistrationTypeEnum fromValue(String value) {
      for (RegistrationTypeEnum b : RegistrationTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_REGISTRATION_TYPE = "registrationType";
  @javax.annotation.Nullable
  private RegistrationTypeEnum registrationType;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  private JsonNullable<String> displayName = JsonNullable.<String>undefined();

  /**
   * requested/changes_requested &#x3D; pre-submission review states; customers see them as pending / needs changes.
   */
  public enum StatusEnum {
    PENDING(String.valueOf("pending")),
    
    APPROVED(String.valueOf("approved")),
    
    REJECTED(String.valueOf("rejected")),
    
    REQUESTED(String.valueOf("requested")),
    
    CHANGES_REQUESTED(String.valueOf("changes_requested")),
    
    DEACTIVATED(String.valueOf("deactivated"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_BRAND_STATUS = "brandStatus";
  @javax.annotation.Nullable
  private String brandStatus;

  public static final String JSON_PROPERTY_CAMPAIGN_STATUS = "campaignStatus";
  @javax.annotation.Nullable
  private String campaignStatus;

  public static final String JSON_PROPERTY_BRAND_ID = "brandId";
  private JsonNullable<String> brandId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CAMPAIGN_ID = "campaignId";
  private JsonNullable<String> campaignId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DECLINE_REASON = "declineReason";
  private JsonNullable<String> declineReason = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TF_ACTION_REQUIRED_AT = "tfActionRequiredAt";
  private JsonNullable<OffsetDateTime> tfActionRequiredAt = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_PHONE_NUMBERS = "phoneNumbers";
  @javax.annotation.Nullable
  private List<String> phoneNumbers = new ArrayList<>();

  public static final String JSON_PROPERTY_AWAITING_OTP = "awaitingOtp";
  @javax.annotation.Nullable
  private Boolean awaitingOtp;

  public static final String JSON_PROPERTY_ADMIN_REVIEW_NOTE = "adminReviewNote";
  private JsonNullable<String> adminReviewNote = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LAST_RESPONSE_AT = "lastResponseAt";
  private JsonNullable<OffsetDateTime> lastResponseAt = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_PREVIOUSLY_REJECTED = "previouslyRejected";
  @javax.annotation.Nullable
  private Boolean previouslyRejected;

  public static final String JSON_PROPERTY_LAST_REJECTED_AT = "lastRejectedAt";
  private JsonNullable<OffsetDateTime> lastRejectedAt = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_REJECTED_BEFORE_SUBMISSION = "rejectedBeforeSubmission";
  @javax.annotation.Nullable
  private Boolean rejectedBeforeSubmission;

  public static final String JSON_PROPERTY_OTP_EXPIRED = "otpExpired";
  @javax.annotation.Nullable
  private Boolean otpExpired;

  public static final String JSON_PROPERTY_REVIEW_REQUEST = "reviewRequest";
  private JsonNullable<SmsRegistrationReviewRequest> reviewRequest = JsonNullable.<SmsRegistrationReviewRequest>undefined();

  public static final String JSON_PROPERTY_TRUST_SCORE = "trustScore";
  private JsonNullable<BigDecimal> trustScore = JsonNullable.<BigDecimal>undefined();

  public static final String JSON_PROPERTY_THROUGHPUT = "throughput";
  @javax.annotation.Nullable
  private ListSmsRegistrations200ResponseRegistrationsInnerThroughput throughput;

  public ListSmsRegistrations200ResponseRegistrationsInner() { 
  }

  public ListSmsRegistrations200ResponseRegistrationsInner id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public ListSmsRegistrations200ResponseRegistrationsInner registrationType(@javax.annotation.Nullable RegistrationTypeEnum registrationType) {
    this.registrationType = registrationType;
    return this;
  }

  /**
   * Get registrationType
   * @return registrationType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REGISTRATION_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RegistrationTypeEnum getRegistrationType() {
    return registrationType;
  }


  @JsonProperty(value = JSON_PROPERTY_REGISTRATION_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegistrationType(@javax.annotation.Nullable RegistrationTypeEnum registrationType) {
    this.registrationType = registrationType;
  }


  public ListSmsRegistrations200ResponseRegistrationsInner displayName(@javax.annotation.Nullable String displayName) {
    this.displayName = JsonNullable.<String>of(displayName);
    return this;
  }

  /**
   * Get displayName
   * @return displayName
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getDisplayName() {
        return displayName.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DISPLAY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDisplayName_JsonNullable() {
    return displayName;
  }
  
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  public void setDisplayName_JsonNullable(JsonNullable<String> displayName) {
    this.displayName = displayName;
  }

  public void setDisplayName(@javax.annotation.Nullable String displayName) {
    this.displayName = JsonNullable.<String>of(displayName);
  }


  public ListSmsRegistrations200ResponseRegistrationsInner status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * requested/changes_requested &#x3D; pre-submission review states; customers see them as pending / needs changes.
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public ListSmsRegistrations200ResponseRegistrationsInner brandStatus(@javax.annotation.Nullable String brandStatus) {
    this.brandStatus = brandStatus;
    return this;
  }

  /**
   * Carrier-registry brand status (e.g. VERIFIED).
   * @return brandStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BRAND_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBrandStatus() {
    return brandStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_BRAND_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBrandStatus(@javax.annotation.Nullable String brandStatus) {
    this.brandStatus = brandStatus;
  }


  public ListSmsRegistrations200ResponseRegistrationsInner campaignStatus(@javax.annotation.Nullable String campaignStatus) {
    this.campaignStatus = campaignStatus;
    return this;
  }

  /**
   * Get campaignStatus
   * @return campaignStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CAMPAIGN_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCampaignStatus() {
    return campaignStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_CAMPAIGN_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCampaignStatus(@javax.annotation.Nullable String campaignStatus) {
    this.campaignStatus = campaignStatus;
  }


  public ListSmsRegistrations200ResponseRegistrationsInner brandId(@javax.annotation.Nullable String brandId) {
    this.brandId = JsonNullable.<String>of(brandId);
    return this;
  }

  /**
   * TCR brand id, useful when referencing the brand in carrier support threads.
   * @return brandId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getBrandId() {
        return brandId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_BRAND_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getBrandId_JsonNullable() {
    return brandId;
  }
  
  @JsonProperty(JSON_PROPERTY_BRAND_ID)
  public void setBrandId_JsonNullable(JsonNullable<String> brandId) {
    this.brandId = brandId;
  }

  public void setBrandId(@javax.annotation.Nullable String brandId) {
    this.brandId = JsonNullable.<String>of(brandId);
  }


  public ListSmsRegistrations200ResponseRegistrationsInner campaignId(@javax.annotation.Nullable String campaignId) {
    this.campaignId = JsonNullable.<String>of(campaignId);
    return this;
  }

  /**
   * TCR campaign id.
   * @return campaignId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getCampaignId() {
        return campaignId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CAMPAIGN_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCampaignId_JsonNullable() {
    return campaignId;
  }
  
  @JsonProperty(JSON_PROPERTY_CAMPAIGN_ID)
  public void setCampaignId_JsonNullable(JsonNullable<String> campaignId) {
    this.campaignId = campaignId;
  }

  public void setCampaignId(@javax.annotation.Nullable String campaignId) {
    this.campaignId = JsonNullable.<String>of(campaignId);
  }


  public ListSmsRegistrations200ResponseRegistrationsInner declineReason(@javax.annotation.Nullable String declineReason) {
    this.declineReason = JsonNullable.<String>of(declineReason);
    return this;
  }

  /**
   * Get declineReason
   * @return declineReason
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getDeclineReason() {
        return declineReason.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DECLINE_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDeclineReason_JsonNullable() {
    return declineReason;
  }
  
  @JsonProperty(JSON_PROPERTY_DECLINE_REASON)
  public void setDeclineReason_JsonNullable(JsonNullable<String> declineReason) {
    this.declineReason = declineReason;
  }

  public void setDeclineReason(@javax.annotation.Nullable String declineReason) {
    this.declineReason = JsonNullable.<String>of(declineReason);
  }


  public ListSmsRegistrations200ResponseRegistrationsInner tfActionRequiredAt(@javax.annotation.Nullable OffsetDateTime tfActionRequiredAt) {
    this.tfActionRequiredAt = JsonNullable.<OffsetDateTime>of(tfActionRequiredAt);
    return this;
  }

  /**
   * Toll-free only: when the carrier requested changes (\&quot;Waiting For Customer\&quot;). The request must be resubmitted within 7 days of this timestamp or it expires.
   * @return tfActionRequiredAt
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public OffsetDateTime getTfActionRequiredAt() {
        return tfActionRequiredAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TF_ACTION_REQUIRED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getTfActionRequiredAt_JsonNullable() {
    return tfActionRequiredAt;
  }
  
  @JsonProperty(JSON_PROPERTY_TF_ACTION_REQUIRED_AT)
  public void setTfActionRequiredAt_JsonNullable(JsonNullable<OffsetDateTime> tfActionRequiredAt) {
    this.tfActionRequiredAt = tfActionRequiredAt;
  }

  public void setTfActionRequiredAt(@javax.annotation.Nullable OffsetDateTime tfActionRequiredAt) {
    this.tfActionRequiredAt = JsonNullable.<OffsetDateTime>of(tfActionRequiredAt);
  }


  public ListSmsRegistrations200ResponseRegistrationsInner phoneNumbers(@javax.annotation.Nullable List<String> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
    return this;
  }

  public ListSmsRegistrations200ResponseRegistrationsInner addPhoneNumbersItem(String phoneNumbersItem) {
    if (this.phoneNumbers == null) {
      this.phoneNumbers = new ArrayList<>();
    }
    this.phoneNumbers.add(phoneNumbersItem);
    return this;
  }

  /**
   * Get phoneNumbers
   * @return phoneNumbers
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PHONE_NUMBERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getPhoneNumbers() {
    return phoneNumbers;
  }


  @JsonProperty(value = JSON_PROPERTY_PHONE_NUMBERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhoneNumbers(@javax.annotation.Nullable List<String> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
  }


  public ListSmsRegistrations200ResponseRegistrationsInner awaitingOtp(@javax.annotation.Nullable Boolean awaitingOtp) {
    this.awaitingOtp = awaitingOtp;
    return this;
  }

  /**
   * Sole-prop 10DLC only; the OTP step is still pending.
   * @return awaitingOtp
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AWAITING_OTP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getAwaitingOtp() {
    return awaitingOtp;
  }


  @JsonProperty(value = JSON_PROPERTY_AWAITING_OTP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAwaitingOtp(@javax.annotation.Nullable Boolean awaitingOtp) {
    this.awaitingOtp = awaitingOtp;
  }


  public ListSmsRegistrations200ResponseRegistrationsInner adminReviewNote(@javax.annotation.Nullable String adminReviewNote) {
    this.adminReviewNote = JsonNullable.<String>of(adminReviewNote);
    return this;
  }

  /**
   * The open change request as text (status changes_requested).
   * @return adminReviewNote
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getAdminReviewNote() {
        return adminReviewNote.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ADMIN_REVIEW_NOTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAdminReviewNote_JsonNullable() {
    return adminReviewNote;
  }
  
  @JsonProperty(JSON_PROPERTY_ADMIN_REVIEW_NOTE)
  public void setAdminReviewNote_JsonNullable(JsonNullable<String> adminReviewNote) {
    this.adminReviewNote = adminReviewNote;
  }

  public void setAdminReviewNote(@javax.annotation.Nullable String adminReviewNote) {
    this.adminReviewNote = JsonNullable.<String>of(adminReviewNote);
  }


  public ListSmsRegistrations200ResponseRegistrationsInner lastResponseAt(@javax.annotation.Nullable OffsetDateTime lastResponseAt) {
    this.lastResponseAt = JsonNullable.<OffsetDateTime>of(lastResponseAt);
    return this;
  }

  /**
   * When you last answered a change request.
   * @return lastResponseAt
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public OffsetDateTime getLastResponseAt() {
        return lastResponseAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LAST_RESPONSE_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getLastResponseAt_JsonNullable() {
    return lastResponseAt;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_RESPONSE_AT)
  public void setLastResponseAt_JsonNullable(JsonNullable<OffsetDateTime> lastResponseAt) {
    this.lastResponseAt = lastResponseAt;
  }

  public void setLastResponseAt(@javax.annotation.Nullable OffsetDateTime lastResponseAt) {
    this.lastResponseAt = JsonNullable.<OffsetDateTime>of(lastResponseAt);
  }


  public ListSmsRegistrations200ResponseRegistrationsInner previouslyRejected(@javax.annotation.Nullable Boolean previouslyRejected) {
    this.previouslyRejected = previouslyRejected;
    return this;
  }

  /**
   * Rejected by the carriers at least once. A pending registration with this set is our fix, back with the carriers.
   * @return previouslyRejected
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREVIOUSLY_REJECTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getPreviouslyRejected() {
    return previouslyRejected;
  }


  @JsonProperty(value = JSON_PROPERTY_PREVIOUSLY_REJECTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreviouslyRejected(@javax.annotation.Nullable Boolean previouslyRejected) {
    this.previouslyRejected = previouslyRejected;
  }


  public ListSmsRegistrations200ResponseRegistrationsInner lastRejectedAt(@javax.annotation.Nullable OffsetDateTime lastRejectedAt) {
    this.lastRejectedAt = JsonNullable.<OffsetDateTime>of(lastRejectedAt);
    return this;
  }

  /**
   * When the carriers last rejected it.
   * @return lastRejectedAt
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public OffsetDateTime getLastRejectedAt() {
        return lastRejectedAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LAST_REJECTED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getLastRejectedAt_JsonNullable() {
    return lastRejectedAt;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_REJECTED_AT)
  public void setLastRejectedAt_JsonNullable(JsonNullable<OffsetDateTime> lastRejectedAt) {
    this.lastRejectedAt = lastRejectedAt;
  }

  public void setLastRejectedAt(@javax.annotation.Nullable OffsetDateTime lastRejectedAt) {
    this.lastRejectedAt = JsonNullable.<OffsetDateTime>of(lastRejectedAt);
  }


  public ListSmsRegistrations200ResponseRegistrationsInner rejectedBeforeSubmission(@javax.annotation.Nullable Boolean rejectedBeforeSubmission) {
    this.rejectedBeforeSubmission = rejectedBeforeSubmission;
    return this;
  }

  /**
   * Rejected in our review before anything was filed with the carriers (not a carrier rejection; nothing to fix or appeal).
   * @return rejectedBeforeSubmission
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REJECTED_BEFORE_SUBMISSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getRejectedBeforeSubmission() {
    return rejectedBeforeSubmission;
  }


  @JsonProperty(value = JSON_PROPERTY_REJECTED_BEFORE_SUBMISSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRejectedBeforeSubmission(@javax.annotation.Nullable Boolean rejectedBeforeSubmission) {
    this.rejectedBeforeSubmission = rejectedBeforeSubmission;
  }


  public ListSmsRegistrations200ResponseRegistrationsInner otpExpired(@javax.annotation.Nullable Boolean otpExpired) {
    this.otpExpired = otpExpired;
    return this;
  }

  /**
   * Sole proprietor only: the verification code was never entered within 30 days. Start SMS setup again; it revives the same brand with no second brand fee.
   * @return otpExpired
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OTP_EXPIRED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getOtpExpired() {
    return otpExpired;
  }


  @JsonProperty(value = JSON_PROPERTY_OTP_EXPIRED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOtpExpired(@javax.annotation.Nullable Boolean otpExpired) {
    this.otpExpired = otpExpired;
  }


  public ListSmsRegistrations200ResponseRegistrationsInner reviewRequest(@javax.annotation.Nullable SmsRegistrationReviewRequest reviewRequest) {
    this.reviewRequest = JsonNullable.<SmsRegistrationReviewRequest>of(reviewRequest);
    return this;
  }

  /**
   * Get reviewRequest
   * @return reviewRequest
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public SmsRegistrationReviewRequest getReviewRequest() {
        return reviewRequest.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_REVIEW_REQUEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<SmsRegistrationReviewRequest> getReviewRequest_JsonNullable() {
    return reviewRequest;
  }
  
  @JsonProperty(JSON_PROPERTY_REVIEW_REQUEST)
  public void setReviewRequest_JsonNullable(JsonNullable<SmsRegistrationReviewRequest> reviewRequest) {
    this.reviewRequest = reviewRequest;
  }

  public void setReviewRequest(@javax.annotation.Nullable SmsRegistrationReviewRequest reviewRequest) {
    this.reviewRequest = JsonNullable.<SmsRegistrationReviewRequest>of(reviewRequest);
  }


  public ListSmsRegistrations200ResponseRegistrationsInner trustScore(@javax.annotation.Nullable BigDecimal trustScore) {
    this.trustScore = JsonNullable.<BigDecimal>of(trustScore);
    return this;
  }

  /**
   * Carrier-assigned brand trust score; drives throughput.
   * @return trustScore
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public BigDecimal getTrustScore() {
        return trustScore.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TRUST_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getTrustScore_JsonNullable() {
    return trustScore;
  }
  
  @JsonProperty(JSON_PROPERTY_TRUST_SCORE)
  public void setTrustScore_JsonNullable(JsonNullable<BigDecimal> trustScore) {
    this.trustScore = trustScore;
  }

  public void setTrustScore(@javax.annotation.Nullable BigDecimal trustScore) {
    this.trustScore = JsonNullable.<BigDecimal>of(trustScore);
  }


  public ListSmsRegistrations200ResponseRegistrationsInner throughput(@javax.annotation.Nullable ListSmsRegistrations200ResponseRegistrationsInnerThroughput throughput) {
    this.throughput = throughput;
    return this;
  }

  /**
   * Get throughput
   * @return throughput
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_THROUGHPUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ListSmsRegistrations200ResponseRegistrationsInnerThroughput getThroughput() {
    return throughput;
  }


  @JsonProperty(value = JSON_PROPERTY_THROUGHPUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThroughput(@javax.annotation.Nullable ListSmsRegistrations200ResponseRegistrationsInnerThroughput throughput) {
    this.throughput = throughput;
  }


  /**
   * Return true if this listSmsRegistrations_200_response_registrations_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListSmsRegistrations200ResponseRegistrationsInner listSmsRegistrations200ResponseRegistrationsInner = (ListSmsRegistrations200ResponseRegistrationsInner) o;
    return Objects.equals(this.id, listSmsRegistrations200ResponseRegistrationsInner.id) &&
        Objects.equals(this.registrationType, listSmsRegistrations200ResponseRegistrationsInner.registrationType) &&
        equalsNullable(this.displayName, listSmsRegistrations200ResponseRegistrationsInner.displayName) &&
        Objects.equals(this.status, listSmsRegistrations200ResponseRegistrationsInner.status) &&
        Objects.equals(this.brandStatus, listSmsRegistrations200ResponseRegistrationsInner.brandStatus) &&
        Objects.equals(this.campaignStatus, listSmsRegistrations200ResponseRegistrationsInner.campaignStatus) &&
        equalsNullable(this.brandId, listSmsRegistrations200ResponseRegistrationsInner.brandId) &&
        equalsNullable(this.campaignId, listSmsRegistrations200ResponseRegistrationsInner.campaignId) &&
        equalsNullable(this.declineReason, listSmsRegistrations200ResponseRegistrationsInner.declineReason) &&
        equalsNullable(this.tfActionRequiredAt, listSmsRegistrations200ResponseRegistrationsInner.tfActionRequiredAt) &&
        Objects.equals(this.phoneNumbers, listSmsRegistrations200ResponseRegistrationsInner.phoneNumbers) &&
        Objects.equals(this.awaitingOtp, listSmsRegistrations200ResponseRegistrationsInner.awaitingOtp) &&
        equalsNullable(this.adminReviewNote, listSmsRegistrations200ResponseRegistrationsInner.adminReviewNote) &&
        equalsNullable(this.lastResponseAt, listSmsRegistrations200ResponseRegistrationsInner.lastResponseAt) &&
        Objects.equals(this.previouslyRejected, listSmsRegistrations200ResponseRegistrationsInner.previouslyRejected) &&
        equalsNullable(this.lastRejectedAt, listSmsRegistrations200ResponseRegistrationsInner.lastRejectedAt) &&
        Objects.equals(this.rejectedBeforeSubmission, listSmsRegistrations200ResponseRegistrationsInner.rejectedBeforeSubmission) &&
        Objects.equals(this.otpExpired, listSmsRegistrations200ResponseRegistrationsInner.otpExpired) &&
        equalsNullable(this.reviewRequest, listSmsRegistrations200ResponseRegistrationsInner.reviewRequest) &&
        equalsNullable(this.trustScore, listSmsRegistrations200ResponseRegistrationsInner.trustScore) &&
        Objects.equals(this.throughput, listSmsRegistrations200ResponseRegistrationsInner.throughput);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, registrationType, hashCodeNullable(displayName), status, brandStatus, campaignStatus, hashCodeNullable(brandId), hashCodeNullable(campaignId), hashCodeNullable(declineReason), hashCodeNullable(tfActionRequiredAt), phoneNumbers, awaitingOtp, hashCodeNullable(adminReviewNote), hashCodeNullable(lastResponseAt), previouslyRejected, hashCodeNullable(lastRejectedAt), rejectedBeforeSubmission, otpExpired, hashCodeNullable(reviewRequest), hashCodeNullable(trustScore), throughput);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListSmsRegistrations200ResponseRegistrationsInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    registrationType: ").append(toIndentedString(registrationType)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    brandStatus: ").append(toIndentedString(brandStatus)).append("\n");
    sb.append("    campaignStatus: ").append(toIndentedString(campaignStatus)).append("\n");
    sb.append("    brandId: ").append(toIndentedString(brandId)).append("\n");
    sb.append("    campaignId: ").append(toIndentedString(campaignId)).append("\n");
    sb.append("    declineReason: ").append(toIndentedString(declineReason)).append("\n");
    sb.append("    tfActionRequiredAt: ").append(toIndentedString(tfActionRequiredAt)).append("\n");
    sb.append("    phoneNumbers: ").append(toIndentedString(phoneNumbers)).append("\n");
    sb.append("    awaitingOtp: ").append(toIndentedString(awaitingOtp)).append("\n");
    sb.append("    adminReviewNote: ").append(toIndentedString(adminReviewNote)).append("\n");
    sb.append("    lastResponseAt: ").append(toIndentedString(lastResponseAt)).append("\n");
    sb.append("    previouslyRejected: ").append(toIndentedString(previouslyRejected)).append("\n");
    sb.append("    lastRejectedAt: ").append(toIndentedString(lastRejectedAt)).append("\n");
    sb.append("    rejectedBeforeSubmission: ").append(toIndentedString(rejectedBeforeSubmission)).append("\n");
    sb.append("    otpExpired: ").append(toIndentedString(otpExpired)).append("\n");
    sb.append("    reviewRequest: ").append(toIndentedString(reviewRequest)).append("\n");
    sb.append("    trustScore: ").append(toIndentedString(trustScore)).append("\n");
    sb.append("    throughput: ").append(toIndentedString(throughput)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `registrationType` to the URL query string
    if (getRegistrationType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sregistrationType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRegistrationType()))));
    }

    // add `displayName` to the URL query string
    if (getDisplayName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdisplayName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDisplayName()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `brandStatus` to the URL query string
    if (getBrandStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbrandStatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBrandStatus()))));
    }

    // add `campaignStatus` to the URL query string
    if (getCampaignStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scampaignStatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCampaignStatus()))));
    }

    // add `brandId` to the URL query string
    if (getBrandId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbrandId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBrandId()))));
    }

    // add `campaignId` to the URL query string
    if (getCampaignId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scampaignId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCampaignId()))));
    }

    // add `declineReason` to the URL query string
    if (getDeclineReason() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdeclineReason%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeclineReason()))));
    }

    // add `tfActionRequiredAt` to the URL query string
    if (getTfActionRequiredAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stfActionRequiredAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTfActionRequiredAt()))));
    }

    // add `phoneNumbers` to the URL query string
    if (getPhoneNumbers() != null) {
      for (int i = 0; i < getPhoneNumbers().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sphoneNumbers%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getPhoneNumbers().get(i)))));
      }
    }

    // add `awaitingOtp` to the URL query string
    if (getAwaitingOtp() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sawaitingOtp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAwaitingOtp()))));
    }

    // add `adminReviewNote` to the URL query string
    if (getAdminReviewNote() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sadminReviewNote%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAdminReviewNote()))));
    }

    // add `lastResponseAt` to the URL query string
    if (getLastResponseAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slastResponseAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastResponseAt()))));
    }

    // add `previouslyRejected` to the URL query string
    if (getPreviouslyRejected() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spreviouslyRejected%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPreviouslyRejected()))));
    }

    // add `lastRejectedAt` to the URL query string
    if (getLastRejectedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slastRejectedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastRejectedAt()))));
    }

    // add `rejectedBeforeSubmission` to the URL query string
    if (getRejectedBeforeSubmission() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srejectedBeforeSubmission%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRejectedBeforeSubmission()))));
    }

    // add `otpExpired` to the URL query string
    if (getOtpExpired() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sotpExpired%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOtpExpired()))));
    }

    // add `reviewRequest` to the URL query string
    if (getReviewRequest() != null) {
      joiner.add(getReviewRequest().toUrlQueryString(prefix + "reviewRequest" + suffix));
    }

    // add `trustScore` to the URL query string
    if (getTrustScore() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%strustScore%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTrustScore()))));
    }

    // add `throughput` to the URL query string
    if (getThroughput() != null) {
      joiner.add(getThroughput().toUrlQueryString(prefix + "throughput" + suffix));
    }

    return joiner.toString();
  }
}

