/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * PurchasePhoneNumberRequest
 */
@JsonPropertyOrder({
  PurchasePhoneNumberRequest.JSON_PROPERTY_PROFILE_ID,
  PurchasePhoneNumberRequest.JSON_PROPERTY_COUNTRY,
  PurchasePhoneNumberRequest.JSON_PROPERTY_CONNECT_WHATSAPP,
  PurchasePhoneNumberRequest.JSON_PROPERTY_WANTS_SMS,
  PurchasePhoneNumberRequest.JSON_PROPERTY_PURCHASE_INTENT_ID,
  PurchasePhoneNumberRequest.JSON_PROPERTY_ALLOW_MULTIPLE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-08T07:15:44.655294751Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class PurchasePhoneNumberRequest {
  public static final String JSON_PROPERTY_PROFILE_ID = "profileId";
  @javax.annotation.Nonnull
  private String profileId;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @javax.annotation.Nullable
  private String country = "US";

  public static final String JSON_PROPERTY_CONNECT_WHATSAPP = "connectWhatsapp";
  @javax.annotation.Nullable
  private Boolean connectWhatsapp = true;

  public static final String JSON_PROPERTY_WANTS_SMS = "wantsSms";
  @javax.annotation.Nullable
  private Boolean wantsSms = false;

  public static final String JSON_PROPERTY_PURCHASE_INTENT_ID = "purchaseIntentId";
  @javax.annotation.Nullable
  private String purchaseIntentId;

  public static final String JSON_PROPERTY_ALLOW_MULTIPLE = "allowMultiple";
  @javax.annotation.Nullable
  private Boolean allowMultiple = false;

  public PurchasePhoneNumberRequest() { 
  }

  public PurchasePhoneNumberRequest profileId(@javax.annotation.Nonnull String profileId) {
    this.profileId = profileId;
    return this;
  }

  /**
   * Profile to associate the number with
   * @return profileId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROFILE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProfileId() {
    return profileId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROFILE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProfileId(@javax.annotation.Nonnull String profileId) {
    this.profileId = profileId;
  }


  public PurchasePhoneNumberRequest country(@javax.annotation.Nullable String country) {
    this.country = country;
    return this;
  }

  /**
   * ISO 3166-1 alpha-2 country for the number (default US). International numbers require usage-based billing. Tier 3/4 countries return 202 { status: \&quot;kyc_required\&quot;, kycUrl } — the customer must complete KYC at that URL before the number is ordered. See GET /v1/phone-numbers/countries. 
   * @return country
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCountry() {
    return country;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }


  public PurchasePhoneNumberRequest connectWhatsapp(@javax.annotation.Nullable Boolean connectWhatsapp) {
    this.connectWhatsapp = connectWhatsapp;
    return this;
  }

  /**
   * A phone number is the unit; WhatsApp is one optional feature. Pass false to buy a STANDALONE number (Calls/SMS only): provisioning skips the Meta pre-verify/OTP steps and the number activates immediately. Omitted defaults to the WhatsApp provisioning path. WhatsApp can be connected to a standalone number later from the connect flow. 
   * @return connectWhatsapp
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONNECT_WHATSAPP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getConnectWhatsapp() {
    return connectWhatsapp;
  }


  @JsonProperty(value = JSON_PROPERTY_CONNECT_WHATSAPP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConnectWhatsapp(@javax.annotation.Nullable Boolean connectWhatsapp) {
    this.connectWhatsapp = connectWhatsapp;
  }


  public PurchasePhoneNumberRequest wantsSms(@javax.annotation.Nullable Boolean wantsSms) {
    this.wantsSms = wantsSms;
    return this;
  }

  /**
   * SMS capability is per-number, not per-country. Pass true to provision from the SMS-capable inventory pool so the number can actually text (see also GET /v1/phone-numbers/available with sms&#x3D;true, and smsAvailable on GET /v1/phone-numbers/countries). 
   * @return wantsSms
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WANTS_SMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getWantsSms() {
    return wantsSms;
  }


  @JsonProperty(value = JSON_PROPERTY_WANTS_SMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWantsSms(@javax.annotation.Nullable Boolean wantsSms) {
    this.wantsSms = wantsSms;
  }


  public PurchasePhoneNumberRequest purchaseIntentId(@javax.annotation.Nullable String purchaseIntentId) {
    this.purchaseIntentId = purchaseIntentId;
    return this;
  }

  /**
   * Optional idempotency key. Send the same value when retrying a purchase: if a number was already bought under this key, the API returns { status: \&quot;already_purchased\&quot;, numberId, phoneNumber } instead of provisioning a second number. Generate a fresh key for each genuinely new purchase. 
   * @return purchaseIntentId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PURCHASE_INTENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPurchaseIntentId() {
    return purchaseIntentId;
  }


  @JsonProperty(value = JSON_PROPERTY_PURCHASE_INTENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPurchaseIntentId(@javax.annotation.Nullable String purchaseIntentId) {
    this.purchaseIntentId = purchaseIntentId;
  }


  public PurchasePhoneNumberRequest allowMultiple(@javax.annotation.Nullable Boolean allowMultiple) {
    this.allowMultiple = allowMultiple;
    return this;
  }

  /**
   * Any second purchase within 10 minutes of a previous one is rejected with 409 code PURCHASE_VELOCITY as duplicate protection. Pass true to confirm the additional purchase is intentional (e.g. bulk provisioning). 
   * @return allowMultiple
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALLOW_MULTIPLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getAllowMultiple() {
    return allowMultiple;
  }


  @JsonProperty(value = JSON_PROPERTY_ALLOW_MULTIPLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowMultiple(@javax.annotation.Nullable Boolean allowMultiple) {
    this.allowMultiple = allowMultiple;
  }


  /**
   * Return true if this purchasePhoneNumber_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PurchasePhoneNumberRequest purchasePhoneNumberRequest = (PurchasePhoneNumberRequest) o;
    return Objects.equals(this.profileId, purchasePhoneNumberRequest.profileId) &&
        Objects.equals(this.country, purchasePhoneNumberRequest.country) &&
        Objects.equals(this.connectWhatsapp, purchasePhoneNumberRequest.connectWhatsapp) &&
        Objects.equals(this.wantsSms, purchasePhoneNumberRequest.wantsSms) &&
        Objects.equals(this.purchaseIntentId, purchasePhoneNumberRequest.purchaseIntentId) &&
        Objects.equals(this.allowMultiple, purchasePhoneNumberRequest.allowMultiple);
  }

  @Override
  public int hashCode() {
    return Objects.hash(profileId, country, connectWhatsapp, wantsSms, purchaseIntentId, allowMultiple);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PurchasePhoneNumberRequest {\n");
    sb.append("    profileId: ").append(toIndentedString(profileId)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    connectWhatsapp: ").append(toIndentedString(connectWhatsapp)).append("\n");
    sb.append("    wantsSms: ").append(toIndentedString(wantsSms)).append("\n");
    sb.append("    purchaseIntentId: ").append(toIndentedString(purchaseIntentId)).append("\n");
    sb.append("    allowMultiple: ").append(toIndentedString(allowMultiple)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `profileId` to the URL query string
    if (getProfileId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprofileId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProfileId()))));
    }

    // add `country` to the URL query string
    if (getCountry() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scountry%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCountry()))));
    }

    // add `connectWhatsapp` to the URL query string
    if (getConnectWhatsapp() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sconnectWhatsapp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getConnectWhatsapp()))));
    }

    // add `wantsSms` to the URL query string
    if (getWantsSms() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swantsSms%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWantsSms()))));
    }

    // add `purchaseIntentId` to the URL query string
    if (getPurchaseIntentId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spurchaseIntentId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPurchaseIntentId()))));
    }

    // add `allowMultiple` to the URL query string
    if (getAllowMultiple() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sallowMultiple%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAllowMultiple()))));
    }

    return joiner.toString();
  }
}

