/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * QueueNextSlotResponse
 */
@JsonPropertyOrder({
  QueueNextSlotResponse.JSON_PROPERTY_PROFILE_ID,
  QueueNextSlotResponse.JSON_PROPERTY_NEXT_SLOT,
  QueueNextSlotResponse.JSON_PROPERTY_TIMEZONE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-23T20:33:07.203614385Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class QueueNextSlotResponse {
  public static final String JSON_PROPERTY_PROFILE_ID = "profileId";
  @javax.annotation.Nullable
  private String profileId;

  public static final String JSON_PROPERTY_NEXT_SLOT = "nextSlot";
  @javax.annotation.Nullable
  private OffsetDateTime nextSlot;

  public static final String JSON_PROPERTY_TIMEZONE = "timezone";
  @javax.annotation.Nullable
  private String timezone;

  public QueueNextSlotResponse() { 
  }

  public QueueNextSlotResponse profileId(@javax.annotation.Nullable String profileId) {
    this.profileId = profileId;
    return this;
  }

  /**
   * Get profileId
   * @return profileId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROFILE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProfileId() {
    return profileId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROFILE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfileId(@javax.annotation.Nullable String profileId) {
    this.profileId = profileId;
  }


  public QueueNextSlotResponse nextSlot(@javax.annotation.Nullable OffsetDateTime nextSlot) {
    this.nextSlot = nextSlot;
    return this;
  }

  /**
   * Get nextSlot
   * @return nextSlot
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NEXT_SLOT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getNextSlot() {
    return nextSlot;
  }


  @JsonProperty(value = JSON_PROPERTY_NEXT_SLOT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextSlot(@javax.annotation.Nullable OffsetDateTime nextSlot) {
    this.nextSlot = nextSlot;
  }


  public QueueNextSlotResponse timezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
    return this;
  }

  /**
   * Get timezone
   * @return timezone
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMEZONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTimezone() {
    return timezone;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMEZONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
  }


  /**
   * Return true if this QueueNextSlotResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueueNextSlotResponse queueNextSlotResponse = (QueueNextSlotResponse) o;
    return Objects.equals(this.profileId, queueNextSlotResponse.profileId) &&
        Objects.equals(this.nextSlot, queueNextSlotResponse.nextSlot) &&
        Objects.equals(this.timezone, queueNextSlotResponse.timezone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(profileId, nextSlot, timezone);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueueNextSlotResponse {\n");
    sb.append("    profileId: ").append(toIndentedString(profileId)).append("\n");
    sb.append("    nextSlot: ").append(toIndentedString(nextSlot)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `profileId` to the URL query string
    if (getProfileId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprofileId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProfileId()))));
    }

    // add `nextSlot` to the URL query string
    if (getNextSlot() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snextSlot%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNextSlot()))));
    }

    // add `timezone` to the URL query string
    if (getTimezone() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimezone%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimezone()))));
    }

    return joiner.toString();
  }
}

