/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.KeywordEntry;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * ReplaceCampaignNegativeKeywordsRequest
 */
@JsonPropertyOrder({
  ReplaceCampaignNegativeKeywordsRequest.JSON_PROPERTY_PLATFORM,
  ReplaceCampaignNegativeKeywordsRequest.JSON_PROPERTY_KEYWORDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-09T13:43:35.323352073Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class ReplaceCampaignNegativeKeywordsRequest {
  /**
   * Optional and NOT authoritative: the resolved campaign&#39;s own platform decides 200 vs 501, never this hint.
   */
  public enum PlatformEnum {
    FACEBOOK(String.valueOf("facebook")),
    
    INSTAGRAM(String.valueOf("instagram")),
    
    TIKTOK(String.valueOf("tiktok")),
    
    LINKEDIN(String.valueOf("linkedin")),
    
    PINTEREST(String.valueOf("pinterest")),
    
    GOOGLE(String.valueOf("google")),
    
    TWITTER(String.valueOf("twitter")),
    
    OPENAI(String.valueOf("openai"));

    private String value;

    PlatformEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PlatformEnum fromValue(String value) {
      for (PlatformEnum b : PlatformEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PLATFORM = "platform";
  @javax.annotation.Nullable
  private PlatformEnum platform;

  public static final String JSON_PROPERTY_KEYWORDS = "keywords";
  @javax.annotation.Nonnull
  private List<KeywordEntry> keywords = new ArrayList<>();

  public ReplaceCampaignNegativeKeywordsRequest() { 
  }

  public ReplaceCampaignNegativeKeywordsRequest platform(@javax.annotation.Nullable PlatformEnum platform) {
    this.platform = platform;
    return this;
  }

  /**
   * Optional and NOT authoritative: the resolved campaign&#39;s own platform decides 200 vs 501, never this hint.
   * @return platform
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PLATFORM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PlatformEnum getPlatform() {
    return platform;
  }


  @JsonProperty(value = JSON_PROPERTY_PLATFORM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlatform(@javax.annotation.Nullable PlatformEnum platform) {
    this.platform = platform;
  }


  public ReplaceCampaignNegativeKeywordsRequest keywords(@javax.annotation.Nonnull List<KeywordEntry> keywords) {
    this.keywords = keywords;
    return this;
  }

  public ReplaceCampaignNegativeKeywordsRequest addKeywordsItem(KeywordEntry keywordsItem) {
    if (this.keywords == null) {
      this.keywords = new ArrayList<>();
    }
    this.keywords.add(keywordsItem);
    return this;
  }

  /**
   * Get keywords
   * @return keywords
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEYWORDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<KeywordEntry> getKeywords() {
    return keywords;
  }


  @JsonProperty(value = JSON_PROPERTY_KEYWORDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKeywords(@javax.annotation.Nonnull List<KeywordEntry> keywords) {
    this.keywords = keywords;
  }


  /**
   * Return true if this replaceCampaignNegativeKeywords_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReplaceCampaignNegativeKeywordsRequest replaceCampaignNegativeKeywordsRequest = (ReplaceCampaignNegativeKeywordsRequest) o;
    return Objects.equals(this.platform, replaceCampaignNegativeKeywordsRequest.platform) &&
        Objects.equals(this.keywords, replaceCampaignNegativeKeywordsRequest.keywords);
  }

  @Override
  public int hashCode() {
    return Objects.hash(platform, keywords);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReplaceCampaignNegativeKeywordsRequest {\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `platform` to the URL query string
    if (getPlatform() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%splatform%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPlatform()))));
    }

    // add `keywords` to the URL query string
    if (getKeywords() != null) {
      for (int i = 0; i < getKeywords().size(); i++) {
        if (getKeywords().get(i) != null) {
          joiner.add(getKeywords().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%skeywords%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

