/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.99.0
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.SmsRegistrationReviewRequestPointsInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * An open change request written as points. Answer each point with POST /v1/sms/registrations/{id}/respond: &#x60;answer&#x60; says what each point needs (text, a link, a hosted document, or a link or a document).
 */
@JsonPropertyOrder({
  SmsRegistrationReviewRequest.JSON_PROPERTY_ID,
  SmsRegistrationReviewRequest.JSON_PROPERTY_INTRO,
  SmsRegistrationReviewRequest.JSON_PROPERTY_POINTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-26T07:26:06.848475649Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class SmsRegistrationReviewRequest {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_INTRO = "intro";
  @javax.annotation.Nullable
  private String intro;

  public static final String JSON_PROPERTY_POINTS = "points";
  @javax.annotation.Nullable
  private List<SmsRegistrationReviewRequestPointsInner> points = new ArrayList<>();

  public SmsRegistrationReviewRequest() { 
  }

  public SmsRegistrationReviewRequest id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Changes with every request. Send it back as &#x60;requestId&#x60; when answering, so a reply to a replaced request is refused (409) instead of filed under the new points.
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public SmsRegistrationReviewRequest intro(@javax.annotation.Nullable String intro) {
    this.intro = intro;
    return this;
  }

  /**
   * Context from the reviewer, e.g. what was already fixed on our side.
   * @return intro
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INTRO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIntro() {
    return intro;
  }


  @JsonProperty(value = JSON_PROPERTY_INTRO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIntro(@javax.annotation.Nullable String intro) {
    this.intro = intro;
  }


  public SmsRegistrationReviewRequest points(@javax.annotation.Nullable List<SmsRegistrationReviewRequestPointsInner> points) {
    this.points = points;
    return this;
  }

  public SmsRegistrationReviewRequest addPointsItem(SmsRegistrationReviewRequestPointsInner pointsItem) {
    if (this.points == null) {
      this.points = new ArrayList<>();
    }
    this.points.add(pointsItem);
    return this;
  }

  /**
   * Get points
   * @return points
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_POINTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<SmsRegistrationReviewRequestPointsInner> getPoints() {
    return points;
  }


  @JsonProperty(value = JSON_PROPERTY_POINTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPoints(@javax.annotation.Nullable List<SmsRegistrationReviewRequestPointsInner> points) {
    this.points = points;
  }


  /**
   * Return true if this SmsRegistrationReviewRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SmsRegistrationReviewRequest smsRegistrationReviewRequest = (SmsRegistrationReviewRequest) o;
    return Objects.equals(this.id, smsRegistrationReviewRequest.id) &&
        Objects.equals(this.intro, smsRegistrationReviewRequest.intro) &&
        Objects.equals(this.points, smsRegistrationReviewRequest.points);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, intro, points);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SmsRegistrationReviewRequest {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    intro: ").append(toIndentedString(intro)).append("\n");
    sb.append("    points: ").append(toIndentedString(points)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `intro` to the URL query string
    if (getIntro() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sintro%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIntro()))));
    }

    // add `points` to the URL query string
    if (getPoints() != null) {
      for (int i = 0; i < getPoints().size(); i++) {
        if (getPoints().get(i) != null) {
          joiner.add(getPoints().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%spoints%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

