/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.232.0
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * Conversion event fields. Each platform stores a subset; a field it does not store answers 400 naming the supported ones.
 */
@JsonPropertyOrder({
  TrackingTagEventInput.JSON_PROPERTY_AD_ACCOUNT_ID,
  TrackingTagEventInput.JSON_PROPERTY_NAME,
  TrackingTagEventInput.JSON_PROPERTY_TYPE,
  TrackingTagEventInput.JSON_PROPERTY_SITE_EVENT,
  TrackingTagEventInput.JSON_PROPERTY_ENABLED,
  TrackingTagEventInput.JSON_PROPERTY_DEFAULT_VALUE,
  TrackingTagEventInput.JSON_PROPERTY_CURRENCY,
  TrackingTagEventInput.JSON_PROPERTY_CLICK_WINDOW_DAYS,
  TrackingTagEventInput.JSON_PROPERTY_VIEW_WINDOW_DAYS,
  TrackingTagEventInput.JSON_PROPERTY_URL_CONTAINS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-10-07T09:19:38.818511839Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class TrackingTagEventInput {
  public static final String JSON_PROPERTY_AD_ACCOUNT_ID = "adAccountId";
  @javax.annotation.Nullable
  private String adAccountId;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nullable
  private String type;

  /**
   * Neutral alternative to &#x60;type&#x60;, mapped to the platform&#39;s closest type.
   */
  public enum SiteEventEnum {
    PAGE_VIEW(String.valueOf("page_view")),
    
    VIEW_CONTENT(String.valueOf("view_content")),
    
    ADD_TO_CART(String.valueOf("add_to_cart")),
    
    SEARCH(String.valueOf("search")),
    
    INITIATE_CHECKOUT(String.valueOf("initiate_checkout")),
    
    ADD_PAYMENT_INFO(String.valueOf("add_payment_info")),
    
    PURCHASE(String.valueOf("purchase"));

    private String value;

    SiteEventEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SiteEventEnum fromValue(String value) {
      for (SiteEventEnum b : SiteEventEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SITE_EVENT = "siteEvent";
  @javax.annotation.Nullable
  private SiteEventEnum siteEvent;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  @javax.annotation.Nullable
  private Boolean enabled;

  public static final String JSON_PROPERTY_DEFAULT_VALUE = "defaultValue";
  @javax.annotation.Nullable
  private BigDecimal defaultValue;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nullable
  private String currency;

  public static final String JSON_PROPERTY_CLICK_WINDOW_DAYS = "clickWindowDays";
  @javax.annotation.Nullable
  private Integer clickWindowDays;

  public static final String JSON_PROPERTY_VIEW_WINDOW_DAYS = "viewWindowDays";
  @javax.annotation.Nullable
  private Integer viewWindowDays;

  public static final String JSON_PROPERTY_URL_CONTAINS = "urlContains";
  @javax.annotation.Nullable
  private String urlContains;

  public TrackingTagEventInput() { 
  }

  public TrackingTagEventInput adAccountId(@javax.annotation.Nullable String adAccountId) {
    this.adAccountId = adAccountId;
    return this;
  }

  /**
   * Scopes the lookup on platforms whose tag ids live inside an ad account.
   * @return adAccountId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AD_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAdAccountId() {
    return adAccountId;
  }


  @JsonProperty(value = JSON_PROPERTY_AD_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdAccountId(@javax.annotation.Nullable String adAccountId) {
    this.adAccountId = adAccountId;
  }


  public TrackingTagEventInput name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public TrackingTagEventInput type(@javax.annotation.Nullable String type) {
    this.type = type;
    return this;
  }

  /**
   * The platform&#39;s own event type enum value (e.g. &#x60;PURCHASE&#x60;).
   * @return type
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@javax.annotation.Nullable String type) {
    this.type = type;
  }


  public TrackingTagEventInput siteEvent(@javax.annotation.Nullable SiteEventEnum siteEvent) {
    this.siteEvent = siteEvent;
    return this;
  }

  /**
   * Neutral alternative to &#x60;type&#x60;, mapped to the platform&#39;s closest type.
   * @return siteEvent
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SITE_EVENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SiteEventEnum getSiteEvent() {
    return siteEvent;
  }


  @JsonProperty(value = JSON_PROPERTY_SITE_EVENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSiteEvent(@javax.annotation.Nullable SiteEventEnum siteEvent) {
    this.siteEvent = siteEvent;
  }


  public TrackingTagEventInput enabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Get enabled
   * @return enabled
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }


  public TrackingTagEventInput defaultValue(@javax.annotation.Nullable BigDecimal defaultValue) {
    this.defaultValue = defaultValue;
    return this;
  }

  /**
   * Get defaultValue
   * minimum: 0
   * @return defaultValue
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEFAULT_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getDefaultValue() {
    return defaultValue;
  }


  @JsonProperty(value = JSON_PROPERTY_DEFAULT_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultValue(@javax.annotation.Nullable BigDecimal defaultValue) {
    this.defaultValue = defaultValue;
  }


  public TrackingTagEventInput currency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * ISO 4217 code.
   * @return currency
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }


  public TrackingTagEventInput clickWindowDays(@javax.annotation.Nullable Integer clickWindowDays) {
    this.clickWindowDays = clickWindowDays;
    return this;
  }

  /**
   * Get clickWindowDays
   * minimum: 1
   * maximum: 365
   * @return clickWindowDays
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLICK_WINDOW_DAYS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getClickWindowDays() {
    return clickWindowDays;
  }


  @JsonProperty(value = JSON_PROPERTY_CLICK_WINDOW_DAYS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClickWindowDays(@javax.annotation.Nullable Integer clickWindowDays) {
    this.clickWindowDays = clickWindowDays;
  }


  public TrackingTagEventInput viewWindowDays(@javax.annotation.Nullable Integer viewWindowDays) {
    this.viewWindowDays = viewWindowDays;
    return this;
  }

  /**
   * Get viewWindowDays
   * minimum: 0
   * maximum: 365
   * @return viewWindowDays
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VIEW_WINDOW_DAYS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getViewWindowDays() {
    return viewWindowDays;
  }


  @JsonProperty(value = JSON_PROPERTY_VIEW_WINDOW_DAYS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setViewWindowDays(@javax.annotation.Nullable Integer viewWindowDays) {
    this.viewWindowDays = viewWindowDays;
  }


  public TrackingTagEventInput urlContains(@javax.annotation.Nullable String urlContains) {
    this.urlContains = urlContains;
    return this;
  }

  /**
   * Fire only on pages whose URL contains this text (case-insensitive).
   * @return urlContains
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_URL_CONTAINS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUrlContains() {
    return urlContains;
  }


  @JsonProperty(value = JSON_PROPERTY_URL_CONTAINS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrlContains(@javax.annotation.Nullable String urlContains) {
    this.urlContains = urlContains;
  }


  /**
   * Return true if this TrackingTagEventInput object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrackingTagEventInput trackingTagEventInput = (TrackingTagEventInput) o;
    return Objects.equals(this.adAccountId, trackingTagEventInput.adAccountId) &&
        Objects.equals(this.name, trackingTagEventInput.name) &&
        Objects.equals(this.type, trackingTagEventInput.type) &&
        Objects.equals(this.siteEvent, trackingTagEventInput.siteEvent) &&
        Objects.equals(this.enabled, trackingTagEventInput.enabled) &&
        Objects.equals(this.defaultValue, trackingTagEventInput.defaultValue) &&
        Objects.equals(this.currency, trackingTagEventInput.currency) &&
        Objects.equals(this.clickWindowDays, trackingTagEventInput.clickWindowDays) &&
        Objects.equals(this.viewWindowDays, trackingTagEventInput.viewWindowDays) &&
        Objects.equals(this.urlContains, trackingTagEventInput.urlContains);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adAccountId, name, type, siteEvent, enabled, defaultValue, currency, clickWindowDays, viewWindowDays, urlContains);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrackingTagEventInput {\n");
    sb.append("    adAccountId: ").append(toIndentedString(adAccountId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    siteEvent: ").append(toIndentedString(siteEvent)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    clickWindowDays: ").append(toIndentedString(clickWindowDays)).append("\n");
    sb.append("    viewWindowDays: ").append(toIndentedString(viewWindowDays)).append("\n");
    sb.append("    urlContains: ").append(toIndentedString(urlContains)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `adAccountId` to the URL query string
    if (getAdAccountId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sadAccountId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAdAccountId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `siteEvent` to the URL query string
    if (getSiteEvent() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssiteEvent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSiteEvent()))));
    }

    // add `enabled` to the URL query string
    if (getEnabled() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%senabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEnabled()))));
    }

    // add `defaultValue` to the URL query string
    if (getDefaultValue() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdefaultValue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDefaultValue()))));
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    // add `clickWindowDays` to the URL query string
    if (getClickWindowDays() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sclickWindowDays%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getClickWindowDays()))));
    }

    // add `viewWindowDays` to the URL query string
    if (getViewWindowDays() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sviewWindowDays%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getViewWindowDays()))));
    }

    // add `urlContains` to the URL query string
    if (getUrlContains() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%surlContains%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUrlContains()))));
    }

    return joiner.toString();
  }
}

