/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * UpdateDiscordSettings200ResponseAccount
 */
@JsonPropertyOrder({
  UpdateDiscordSettings200ResponseAccount.JSON_PROPERTY_ID,
  UpdateDiscordSettings200ResponseAccount.JSON_PROPERTY_PLATFORM,
  UpdateDiscordSettings200ResponseAccount.JSON_PROPERTY_USERNAME,
  UpdateDiscordSettings200ResponseAccount.JSON_PROPERTY_DISPLAY_NAME,
  UpdateDiscordSettings200ResponseAccount.JSON_PROPERTY_PROFILE_PICTURE,
  UpdateDiscordSettings200ResponseAccount.JSON_PROPERTY_CHANNEL_ID,
  UpdateDiscordSettings200ResponseAccount.JSON_PROPERTY_CHANNEL_NAME,
  UpdateDiscordSettings200ResponseAccount.JSON_PROPERTY_CHANNEL_TYPE,
  UpdateDiscordSettings200ResponseAccount.JSON_PROPERTY_GUILD_ID,
  UpdateDiscordSettings200ResponseAccount.JSON_PROPERTY_WEBHOOK_USERNAME,
  UpdateDiscordSettings200ResponseAccount.JSON_PROPERTY_WEBHOOK_AVATAR_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T17:38:50.674145970Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class UpdateDiscordSettings200ResponseAccount {
  public static final String JSON_PROPERTY_ID = "_id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_PLATFORM = "platform";
  @javax.annotation.Nullable
  private String platform;

  public static final String JSON_PROPERTY_USERNAME = "username";
  @javax.annotation.Nullable
  private String username;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  @javax.annotation.Nullable
  private String displayName;

  public static final String JSON_PROPERTY_PROFILE_PICTURE = "profilePicture";
  @javax.annotation.Nullable
  private String profilePicture;

  public static final String JSON_PROPERTY_CHANNEL_ID = "channelId";
  @javax.annotation.Nullable
  private String channelId;

  public static final String JSON_PROPERTY_CHANNEL_NAME = "channelName";
  @javax.annotation.Nullable
  private String channelName;

  public static final String JSON_PROPERTY_CHANNEL_TYPE = "channelType";
  @javax.annotation.Nullable
  private String channelType;

  public static final String JSON_PROPERTY_GUILD_ID = "guildId";
  @javax.annotation.Nullable
  private String guildId;

  public static final String JSON_PROPERTY_WEBHOOK_USERNAME = "webhookUsername";
  @javax.annotation.Nullable
  private String webhookUsername;

  public static final String JSON_PROPERTY_WEBHOOK_AVATAR_URL = "webhookAvatarUrl";
  @javax.annotation.Nullable
  private String webhookAvatarUrl;

  public UpdateDiscordSettings200ResponseAccount() { 
  }

  public UpdateDiscordSettings200ResponseAccount id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public UpdateDiscordSettings200ResponseAccount platform(@javax.annotation.Nullable String platform) {
    this.platform = platform;
    return this;
  }

  /**
   * Get platform
   * @return platform
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PLATFORM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPlatform() {
    return platform;
  }


  @JsonProperty(value = JSON_PROPERTY_PLATFORM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlatform(@javax.annotation.Nullable String platform) {
    this.platform = platform;
  }


  public UpdateDiscordSettings200ResponseAccount username(@javax.annotation.Nullable String username) {
    this.username = username;
    return this;
  }

  /**
   * Get username
   * @return username
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USERNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUsername() {
    return username;
  }


  @JsonProperty(value = JSON_PROPERTY_USERNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsername(@javax.annotation.Nullable String username) {
    this.username = username;
  }


  public UpdateDiscordSettings200ResponseAccount displayName(@javax.annotation.Nullable String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * Get displayName
   * @return displayName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DISPLAY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(value = JSON_PROPERTY_DISPLAY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayName(@javax.annotation.Nullable String displayName) {
    this.displayName = displayName;
  }


  public UpdateDiscordSettings200ResponseAccount profilePicture(@javax.annotation.Nullable String profilePicture) {
    this.profilePicture = profilePicture;
    return this;
  }

  /**
   * Get profilePicture
   * @return profilePicture
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROFILE_PICTURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProfilePicture() {
    return profilePicture;
  }


  @JsonProperty(value = JSON_PROPERTY_PROFILE_PICTURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfilePicture(@javax.annotation.Nullable String profilePicture) {
    this.profilePicture = profilePicture;
  }


  public UpdateDiscordSettings200ResponseAccount channelId(@javax.annotation.Nullable String channelId) {
    this.channelId = channelId;
    return this;
  }

  /**
   * Get channelId
   * @return channelId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHANNEL_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getChannelId() {
    return channelId;
  }


  @JsonProperty(value = JSON_PROPERTY_CHANNEL_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChannelId(@javax.annotation.Nullable String channelId) {
    this.channelId = channelId;
  }


  public UpdateDiscordSettings200ResponseAccount channelName(@javax.annotation.Nullable String channelName) {
    this.channelName = channelName;
    return this;
  }

  /**
   * Get channelName
   * @return channelName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHANNEL_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getChannelName() {
    return channelName;
  }


  @JsonProperty(value = JSON_PROPERTY_CHANNEL_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChannelName(@javax.annotation.Nullable String channelName) {
    this.channelName = channelName;
  }


  public UpdateDiscordSettings200ResponseAccount channelType(@javax.annotation.Nullable String channelType) {
    this.channelType = channelType;
    return this;
  }

  /**
   * Get channelType
   * @return channelType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHANNEL_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getChannelType() {
    return channelType;
  }


  @JsonProperty(value = JSON_PROPERTY_CHANNEL_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChannelType(@javax.annotation.Nullable String channelType) {
    this.channelType = channelType;
  }


  public UpdateDiscordSettings200ResponseAccount guildId(@javax.annotation.Nullable String guildId) {
    this.guildId = guildId;
    return this;
  }

  /**
   * Get guildId
   * @return guildId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GUILD_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getGuildId() {
    return guildId;
  }


  @JsonProperty(value = JSON_PROPERTY_GUILD_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGuildId(@javax.annotation.Nullable String guildId) {
    this.guildId = guildId;
  }


  public UpdateDiscordSettings200ResponseAccount webhookUsername(@javax.annotation.Nullable String webhookUsername) {
    this.webhookUsername = webhookUsername;
    return this;
  }

  /**
   * Get webhookUsername
   * @return webhookUsername
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEBHOOK_USERNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getWebhookUsername() {
    return webhookUsername;
  }


  @JsonProperty(value = JSON_PROPERTY_WEBHOOK_USERNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebhookUsername(@javax.annotation.Nullable String webhookUsername) {
    this.webhookUsername = webhookUsername;
  }


  public UpdateDiscordSettings200ResponseAccount webhookAvatarUrl(@javax.annotation.Nullable String webhookAvatarUrl) {
    this.webhookAvatarUrl = webhookAvatarUrl;
    return this;
  }

  /**
   * Get webhookAvatarUrl
   * @return webhookAvatarUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEBHOOK_AVATAR_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getWebhookAvatarUrl() {
    return webhookAvatarUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_WEBHOOK_AVATAR_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebhookAvatarUrl(@javax.annotation.Nullable String webhookAvatarUrl) {
    this.webhookAvatarUrl = webhookAvatarUrl;
  }


  /**
   * Return true if this updateDiscordSettings_200_response_account object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateDiscordSettings200ResponseAccount updateDiscordSettings200ResponseAccount = (UpdateDiscordSettings200ResponseAccount) o;
    return Objects.equals(this.id, updateDiscordSettings200ResponseAccount.id) &&
        Objects.equals(this.platform, updateDiscordSettings200ResponseAccount.platform) &&
        Objects.equals(this.username, updateDiscordSettings200ResponseAccount.username) &&
        Objects.equals(this.displayName, updateDiscordSettings200ResponseAccount.displayName) &&
        Objects.equals(this.profilePicture, updateDiscordSettings200ResponseAccount.profilePicture) &&
        Objects.equals(this.channelId, updateDiscordSettings200ResponseAccount.channelId) &&
        Objects.equals(this.channelName, updateDiscordSettings200ResponseAccount.channelName) &&
        Objects.equals(this.channelType, updateDiscordSettings200ResponseAccount.channelType) &&
        Objects.equals(this.guildId, updateDiscordSettings200ResponseAccount.guildId) &&
        Objects.equals(this.webhookUsername, updateDiscordSettings200ResponseAccount.webhookUsername) &&
        Objects.equals(this.webhookAvatarUrl, updateDiscordSettings200ResponseAccount.webhookAvatarUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, platform, username, displayName, profilePicture, channelId, channelName, channelType, guildId, webhookUsername, webhookAvatarUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateDiscordSettings200ResponseAccount {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    profilePicture: ").append(toIndentedString(profilePicture)).append("\n");
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    channelName: ").append(toIndentedString(channelName)).append("\n");
    sb.append("    channelType: ").append(toIndentedString(channelType)).append("\n");
    sb.append("    guildId: ").append(toIndentedString(guildId)).append("\n");
    sb.append("    webhookUsername: ").append(toIndentedString(webhookUsername)).append("\n");
    sb.append("    webhookAvatarUrl: ").append(toIndentedString(webhookAvatarUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `_id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%s_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `platform` to the URL query string
    if (getPlatform() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%splatform%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPlatform()))));
    }

    // add `username` to the URL query string
    if (getUsername() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%susername%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUsername()))));
    }

    // add `displayName` to the URL query string
    if (getDisplayName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdisplayName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDisplayName()))));
    }

    // add `profilePicture` to the URL query string
    if (getProfilePicture() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprofilePicture%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProfilePicture()))));
    }

    // add `channelId` to the URL query string
    if (getChannelId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schannelId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChannelId()))));
    }

    // add `channelName` to the URL query string
    if (getChannelName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schannelName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChannelName()))));
    }

    // add `channelType` to the URL query string
    if (getChannelType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schannelType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChannelType()))));
    }

    // add `guildId` to the URL query string
    if (getGuildId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sguildId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGuildId()))));
    }

    // add `webhookUsername` to the URL query string
    if (getWebhookUsername() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swebhookUsername%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWebhookUsername()))));
    }

    // add `webhookAvatarUrl` to the URL query string
    if (getWebhookAvatarUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swebhookAvatarUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWebhookAvatarUrl()))));
    }

    return joiner.toString();
  }
}

