/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.UpdateGoogleBusinessLocationDetailsRequestRegularHoursPeriodsInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * UpdateGoogleBusinessLocationDetailsRequestMoreHoursInner
 */
@JsonPropertyOrder({
  UpdateGoogleBusinessLocationDetailsRequestMoreHoursInner.JSON_PROPERTY_HOURS_TYPE_ID,
  UpdateGoogleBusinessLocationDetailsRequestMoreHoursInner.JSON_PROPERTY_PERIODS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-09T15:23:23.334871925Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class UpdateGoogleBusinessLocationDetailsRequestMoreHoursInner {
  public static final String JSON_PROPERTY_HOURS_TYPE_ID = "hoursTypeId";
  @javax.annotation.Nullable
  private String hoursTypeId;

  public static final String JSON_PROPERTY_PERIODS = "periods";
  @javax.annotation.Nullable
  private List<UpdateGoogleBusinessLocationDetailsRequestRegularHoursPeriodsInner> periods = new ArrayList<>();

  public UpdateGoogleBusinessLocationDetailsRequestMoreHoursInner() { 
  }

  public UpdateGoogleBusinessLocationDetailsRequestMoreHoursInner hoursTypeId(@javax.annotation.Nullable String hoursTypeId) {
    this.hoursTypeId = hoursTypeId;
    return this;
  }

  /**
   * Hours type from Google&#39;s catalog (e.g. &#39;DELIVERY&#39;, &#39;DRIVE_THROUGH&#39;)
   * @return hoursTypeId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HOURS_TYPE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHoursTypeId() {
    return hoursTypeId;
  }


  @JsonProperty(value = JSON_PROPERTY_HOURS_TYPE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHoursTypeId(@javax.annotation.Nullable String hoursTypeId) {
    this.hoursTypeId = hoursTypeId;
  }


  public UpdateGoogleBusinessLocationDetailsRequestMoreHoursInner periods(@javax.annotation.Nullable List<UpdateGoogleBusinessLocationDetailsRequestRegularHoursPeriodsInner> periods) {
    this.periods = periods;
    return this;
  }

  public UpdateGoogleBusinessLocationDetailsRequestMoreHoursInner addPeriodsItem(UpdateGoogleBusinessLocationDetailsRequestRegularHoursPeriodsInner periodsItem) {
    if (this.periods == null) {
      this.periods = new ArrayList<>();
    }
    this.periods.add(periodsItem);
    return this;
  }

  /**
   * Get periods
   * @return periods
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PERIODS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<UpdateGoogleBusinessLocationDetailsRequestRegularHoursPeriodsInner> getPeriods() {
    return periods;
  }


  @JsonProperty(value = JSON_PROPERTY_PERIODS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPeriods(@javax.annotation.Nullable List<UpdateGoogleBusinessLocationDetailsRequestRegularHoursPeriodsInner> periods) {
    this.periods = periods;
  }


  /**
   * Return true if this updateGoogleBusinessLocationDetails_request_moreHours_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateGoogleBusinessLocationDetailsRequestMoreHoursInner updateGoogleBusinessLocationDetailsRequestMoreHoursInner = (UpdateGoogleBusinessLocationDetailsRequestMoreHoursInner) o;
    return Objects.equals(this.hoursTypeId, updateGoogleBusinessLocationDetailsRequestMoreHoursInner.hoursTypeId) &&
        Objects.equals(this.periods, updateGoogleBusinessLocationDetailsRequestMoreHoursInner.periods);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hoursTypeId, periods);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateGoogleBusinessLocationDetailsRequestMoreHoursInner {\n");
    sb.append("    hoursTypeId: ").append(toIndentedString(hoursTypeId)).append("\n");
    sb.append("    periods: ").append(toIndentedString(periods)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `hoursTypeId` to the URL query string
    if (getHoursTypeId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shoursTypeId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHoursTypeId()))));
    }

    // add `periods` to the URL query string
    if (getPeriods() != null) {
      for (int i = 0; i < getPeriods().size(); i++) {
        if (getPeriods().get(i) != null) {
          joiner.add(getPeriods().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%speriods%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

