/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.WebhookPayloadCommentCommentAuthor;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * WebhookPayloadCommentComment
 */
@JsonPropertyOrder({
  WebhookPayloadCommentComment.JSON_PROPERTY_ID,
  WebhookPayloadCommentComment.JSON_PROPERTY_POST_ID,
  WebhookPayloadCommentComment.JSON_PROPERTY_PLATFORM_POST_ID,
  WebhookPayloadCommentComment.JSON_PROPERTY_PLATFORM,
  WebhookPayloadCommentComment.JSON_PROPERTY_TEXT,
  WebhookPayloadCommentComment.JSON_PROPERTY_AUTHOR,
  WebhookPayloadCommentComment.JSON_PROPERTY_CREATED_AT,
  WebhookPayloadCommentComment.JSON_PROPERTY_IS_REPLY,
  WebhookPayloadCommentComment.JSON_PROPERTY_PARENT_COMMENT_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-21T13:00:40.109374164Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class WebhookPayloadCommentComment {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_POST_ID = "postId";
  @javax.annotation.Nullable
  private String postId;

  public static final String JSON_PROPERTY_PLATFORM_POST_ID = "platformPostId";
  @javax.annotation.Nullable
  private String platformPostId;

  /**
   * Gets or Sets platform
   */
  public enum PlatformEnum {
    INSTAGRAM(String.valueOf("instagram")),
    
    FACEBOOK(String.valueOf("facebook")),
    
    TWITTER(String.valueOf("twitter")),
    
    YOUTUBE(String.valueOf("youtube")),
    
    LINKEDIN(String.valueOf("linkedin")),
    
    BLUESKY(String.valueOf("bluesky")),
    
    REDDIT(String.valueOf("reddit"));

    private String value;

    PlatformEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PlatformEnum fromValue(String value) {
      for (PlatformEnum b : PlatformEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PLATFORM = "platform";
  @javax.annotation.Nullable
  private PlatformEnum platform;

  public static final String JSON_PROPERTY_TEXT = "text";
  @javax.annotation.Nullable
  private String text;

  public static final String JSON_PROPERTY_AUTHOR = "author";
  @javax.annotation.Nullable
  private WebhookPayloadCommentCommentAuthor author;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_IS_REPLY = "isReply";
  @javax.annotation.Nullable
  private Boolean isReply;

  public static final String JSON_PROPERTY_PARENT_COMMENT_ID = "parentCommentId";
  @javax.annotation.Nullable
  private String parentCommentId;

  public WebhookPayloadCommentComment() { 
  }

  public WebhookPayloadCommentComment id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Platform comment ID
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public WebhookPayloadCommentComment postId(@javax.annotation.Nullable String postId) {
    this.postId = postId;
    return this;
  }

  /**
   * Internal post ID
   * @return postId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_POST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPostId() {
    return postId;
  }


  @JsonProperty(value = JSON_PROPERTY_POST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPostId(@javax.annotation.Nullable String postId) {
    this.postId = postId;
  }


  public WebhookPayloadCommentComment platformPostId(@javax.annotation.Nullable String platformPostId) {
    this.platformPostId = platformPostId;
    return this;
  }

  /**
   * Platform&#39;s post ID
   * @return platformPostId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PLATFORM_POST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPlatformPostId() {
    return platformPostId;
  }


  @JsonProperty(value = JSON_PROPERTY_PLATFORM_POST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlatformPostId(@javax.annotation.Nullable String platformPostId) {
    this.platformPostId = platformPostId;
  }


  public WebhookPayloadCommentComment platform(@javax.annotation.Nullable PlatformEnum platform) {
    this.platform = platform;
    return this;
  }

  /**
   * Get platform
   * @return platform
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PLATFORM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PlatformEnum getPlatform() {
    return platform;
  }


  @JsonProperty(value = JSON_PROPERTY_PLATFORM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlatform(@javax.annotation.Nullable PlatformEnum platform) {
    this.platform = platform;
  }


  public WebhookPayloadCommentComment text(@javax.annotation.Nullable String text) {
    this.text = text;
    return this;
  }

  /**
   * Comment text content
   * @return text
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getText() {
    return text;
  }


  @JsonProperty(value = JSON_PROPERTY_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setText(@javax.annotation.Nullable String text) {
    this.text = text;
  }


  public WebhookPayloadCommentComment author(@javax.annotation.Nullable WebhookPayloadCommentCommentAuthor author) {
    this.author = author;
    return this;
  }

  /**
   * Get author
   * @return author
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUTHOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public WebhookPayloadCommentCommentAuthor getAuthor() {
    return author;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTHOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthor(@javax.annotation.Nullable WebhookPayloadCommentCommentAuthor author) {
    this.author = author;
  }


  public WebhookPayloadCommentComment createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public WebhookPayloadCommentComment isReply(@javax.annotation.Nullable Boolean isReply) {
    this.isReply = isReply;
    return this;
  }

  /**
   * Whether this is a reply to another comment
   * @return isReply
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_REPLY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsReply() {
    return isReply;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_REPLY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsReply(@javax.annotation.Nullable Boolean isReply) {
    this.isReply = isReply;
  }


  public WebhookPayloadCommentComment parentCommentId(@javax.annotation.Nullable String parentCommentId) {
    this.parentCommentId = parentCommentId;
    return this;
  }

  /**
   * Parent comment ID if this is a reply
   * @return parentCommentId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PARENT_COMMENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getParentCommentId() {
    return parentCommentId;
  }


  @JsonProperty(value = JSON_PROPERTY_PARENT_COMMENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParentCommentId(@javax.annotation.Nullable String parentCommentId) {
    this.parentCommentId = parentCommentId;
  }


  /**
   * Return true if this WebhookPayloadComment_comment object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookPayloadCommentComment webhookPayloadCommentComment = (WebhookPayloadCommentComment) o;
    return Objects.equals(this.id, webhookPayloadCommentComment.id) &&
        Objects.equals(this.postId, webhookPayloadCommentComment.postId) &&
        Objects.equals(this.platformPostId, webhookPayloadCommentComment.platformPostId) &&
        Objects.equals(this.platform, webhookPayloadCommentComment.platform) &&
        Objects.equals(this.text, webhookPayloadCommentComment.text) &&
        Objects.equals(this.author, webhookPayloadCommentComment.author) &&
        Objects.equals(this.createdAt, webhookPayloadCommentComment.createdAt) &&
        Objects.equals(this.isReply, webhookPayloadCommentComment.isReply) &&
        Objects.equals(this.parentCommentId, webhookPayloadCommentComment.parentCommentId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, postId, platformPostId, platform, text, author, createdAt, isReply, parentCommentId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookPayloadCommentComment {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    postId: ").append(toIndentedString(postId)).append("\n");
    sb.append("    platformPostId: ").append(toIndentedString(platformPostId)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    isReply: ").append(toIndentedString(isReply)).append("\n");
    sb.append("    parentCommentId: ").append(toIndentedString(parentCommentId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `postId` to the URL query string
    if (getPostId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spostId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPostId()))));
    }

    // add `platformPostId` to the URL query string
    if (getPlatformPostId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%splatformPostId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPlatformPostId()))));
    }

    // add `platform` to the URL query string
    if (getPlatform() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%splatform%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPlatform()))));
    }

    // add `text` to the URL query string
    if (getText() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stext%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getText()))));
    }

    // add `author` to the URL query string
    if (getAuthor() != null) {
      joiner.add(getAuthor().toUrlQueryString(prefix + "author" + suffix));
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `isReply` to the URL query string
    if (getIsReply() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sisReply%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsReply()))));
    }

    // add `parentCommentId` to the URL query string
    if (getParentCommentId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sparentCommentId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getParentCommentId()))));
    }

    return joiner.toString();
  }
}

