/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.193.0
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.ApiChangelogOperationRef;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiChangelogEntryChangesEndpoints
 */
class ApiChangelogEntryChangesEndpointsTest {
    private final ApiChangelogEntryChangesEndpoints model = new ApiChangelogEntryChangesEndpoints();

    /**
     * Model tests for ApiChangelogEntryChangesEndpoints
     */
    @Test
    void testApiChangelogEntryChangesEndpoints() {
        // TODO: test ApiChangelogEntryChangesEndpoints
    }

    /**
     * Test the property 'added'
     */
    @Test
    void addedTest() {
        // TODO: test added
    }

    /**
     * Test the property 'removed'
     */
    @Test
    void removedTest() {
        // TODO: test removed
    }

    /**
     * Test the property 'modified'
     */
    @Test
    void modifiedTest() {
        // TODO: test modified
    }

}
