/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CheckInstagramHashtags200ResponseSummary
 */
class CheckInstagramHashtags200ResponseSummaryTest {
    private final CheckInstagramHashtags200ResponseSummary model = new CheckInstagramHashtags200ResponseSummary();

    /**
     * Model tests for CheckInstagramHashtags200ResponseSummary
     */
    @Test
    void testCheckInstagramHashtags200ResponseSummary() {
        // TODO: test CheckInstagramHashtags200ResponseSummary
    }

    /**
     * Test the property 'banned'
     */
    @Test
    void bannedTest() {
        // TODO: test banned
    }

    /**
     * Test the property 'restricted'
     */
    @Test
    void restrictedTest() {
        // TODO: test restricted
    }

    /**
     * Test the property 'safe'
     */
    @Test
    void safeTest() {
        // TODO: test safe
    }

}
