/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.149.0
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.CommerceImage;
import dev.zernio.model.CommerceProductStatus;
import dev.zernio.model.CommerceVariant;
import dev.zernio.model.ProductOptionsInner;
import dev.zernio.model.ProductSeo;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CommerceProduct
 */
class CommerceProductTest {
    private final CommerceProduct model = new CommerceProduct();

    /**
     * Model tests for CommerceProduct
     */
    @Test
    void testCommerceProduct() {
        // TODO: test CommerceProduct
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'platform'
     */
    @Test
    void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'title'
     */
    @Test
    void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'descriptionHtml'
     */
    @Test
    void descriptionHtmlTest() {
        // TODO: test descriptionHtml
    }

    /**
     * Test the property 'handle'
     */
    @Test
    void handleTest() {
        // TODO: test handle
    }

    /**
     * Test the property 'vendor'
     */
    @Test
    void vendorTest() {
        // TODO: test vendor
    }

    /**
     * Test the property 'productType'
     */
    @Test
    void productTypeTest() {
        // TODO: test productType
    }

    /**
     * Test the property 'tags'
     */
    @Test
    void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'platformStatus'
     */
    @Test
    void platformStatusTest() {
        // TODO: test platformStatus
    }

    /**
     * Test the property 'featuredImage'
     */
    @Test
    void featuredImageTest() {
        // TODO: test featuredImage
    }

    /**
     * Test the property 'images'
     */
    @Test
    void imagesTest() {
        // TODO: test images
    }

    /**
     * Test the property 'options'
     */
    @Test
    void optionsTest() {
        // TODO: test options
    }

    /**
     * Test the property 'variants'
     */
    @Test
    void variantsTest() {
        // TODO: test variants
    }

    /**
     * Test the property 'totalInventory'
     */
    @Test
    void totalInventoryTest() {
        // TODO: test totalInventory
    }

    /**
     * Test the property 'url'
     */
    @Test
    void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'seo'
     */
    @Test
    void seoTest() {
        // TODO: test seo
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'publishedAt'
     */
    @Test
    void publishedAtTest() {
        // TODO: test publishedAt
    }

    /**
     * Test the property 'platformData'
     */
    @Test
    void platformDataTest() {
        // TODO: test platformData
    }

}
