/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DuplicateAdCampaign200Response
 */
class DuplicateAdCampaign200ResponseTest {
    private final DuplicateAdCampaign200Response model = new DuplicateAdCampaign200Response();

    /**
     * Model tests for DuplicateAdCampaign200Response
     */
    @Test
    void testDuplicateAdCampaign200Response() {
        // TODO: test DuplicateAdCampaign200Response
    }

    /**
     * Test the property 'copiedCampaignId'
     */
    @Test
    void copiedCampaignIdTest() {
        // TODO: test copiedCampaignId
    }

    /**
     * Test the property 'discovery'
     */
    @Test
    void discoveryTest() {
        // TODO: test discovery
    }

    /**
     * Test the property 'raw'
     */
    @Test
    void rawTest() {
        // TODO: test raw
    }

}
