/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetAdComments200ResponsePagination
 */
class GetAdComments200ResponsePaginationTest {
    private final GetAdComments200ResponsePagination model = new GetAdComments200ResponsePagination();

    /**
     * Model tests for GetAdComments200ResponsePagination
     */
    @Test
    void testGetAdComments200ResponsePagination() {
        // TODO: test GetAdComments200ResponsePagination
    }

    /**
     * Test the property 'hasMore'
     */
    @Test
    void hasMoreTest() {
        // TODO: test hasMore
    }

    /**
     * Test the property 'cursor'
     */
    @Test
    void cursorTest() {
        // TODO: test cursor
    }

}
