/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetConversionsQuality200ResponseRowsInnerMatchKeysInner
 */
class GetConversionsQuality200ResponseRowsInnerMatchKeysInnerTest {
    private final GetConversionsQuality200ResponseRowsInnerMatchKeysInner model = new GetConversionsQuality200ResponseRowsInnerMatchKeysInner();

    /**
     * Model tests for GetConversionsQuality200ResponseRowsInnerMatchKeysInner
     */
    @Test
    void testGetConversionsQuality200ResponseRowsInnerMatchKeysInner() {
        // TODO: test GetConversionsQuality200ResponseRowsInnerMatchKeysInner
    }

    /**
     * Test the property 'identifier'
     */
    @Test
    void identifierTest() {
        // TODO: test identifier
    }

    /**
     * Test the property 'coveragePercentage'
     */
    @Test
    void coveragePercentageTest() {
        // TODO: test coveragePercentage
    }

}
