/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.GetCampaignAnalytics200ResponseAnalytics;
import dev.zernio.model.GetCampaignAnalytics200ResponseCampaign;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetCampaignAnalytics200Response
 */
class GetCampaignAnalytics200ResponseTest {
    private final GetCampaignAnalytics200Response model = new GetCampaignAnalytics200Response();

    /**
     * Model tests for GetCampaignAnalytics200Response
     */
    @Test
    void testGetCampaignAnalytics200Response() {
        // TODO: test GetCampaignAnalytics200Response
    }

    /**
     * Test the property 'campaign'
     */
    @Test
    void campaignTest() {
        // TODO: test campaign
    }

    /**
     * Test the property 'analytics'
     */
    @Test
    void analyticsTest() {
        // TODO: test analytics
    }

}
