/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.GetLeadForm200ResponseFormQuestionsInner;
import dev.zernio.model.GetLeadForm200ResponseFormThankYouPage;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetLeadForm200ResponseForm
 */
class GetLeadForm200ResponseFormTest {
    private final GetLeadForm200ResponseForm model = new GetLeadForm200ResponseForm();

    /**
     * Model tests for GetLeadForm200ResponseForm
     */
    @Test
    void testGetLeadForm200ResponseForm() {
        // TODO: test GetLeadForm200ResponseForm
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'locale'
     */
    @Test
    void localeTest() {
        // TODO: test locale
    }

    /**
     * Test the property 'createdTime'
     */
    @Test
    void createdTimeTest() {
        // TODO: test createdTime
    }

    /**
     * Test the property 'leadsCount'
     */
    @Test
    void leadsCountTest() {
        // TODO: test leadsCount
    }

    /**
     * Test the property 'privacyPolicyUrl'
     */
    @Test
    void privacyPolicyUrlTest() {
        // TODO: test privacyPolicyUrl
    }

    /**
     * Test the property 'followUpActionUrl'
     */
    @Test
    void followUpActionUrlTest() {
        // TODO: test followUpActionUrl
    }

    /**
     * Test the property 'questions'
     */
    @Test
    void questionsTest() {
        // TODO: test questions
    }

    /**
     * Test the property 'thankYouPage'
     */
    @Test
    void thankYouPageTest() {
        // TODO: test thankYouPage
    }

    /**
     * Test the property 'contextCard'
     */
    @Test
    void contextCardTest() {
        // TODO: test contextCard
    }

}
