/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.GetWhatsAppContacts200ResponseContactsInner;
import dev.zernio.model.GetWhatsAppContacts200ResponseFilters;
import dev.zernio.model.GetWhatsAppContacts200ResponsePagination;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetWhatsAppContacts200Response
 */
class GetWhatsAppContacts200ResponseTest {
    private final GetWhatsAppContacts200Response model = new GetWhatsAppContacts200Response();

    /**
     * Model tests for GetWhatsAppContacts200Response
     */
    @Test
    void testGetWhatsAppContacts200Response() {
        // TODO: test GetWhatsAppContacts200Response
    }

    /**
     * Test the property 'success'
     */
    @Test
    void successTest() {
        // TODO: test success
    }

    /**
     * Test the property 'contacts'
     */
    @Test
    void contactsTest() {
        // TODO: test contacts
    }

    /**
     * Test the property 'filters'
     */
    @Test
    void filtersTest() {
        // TODO: test filters
    }

    /**
     * Test the property 'pagination'
     */
    @Test
    void paginationTest() {
        // TODO: test pagination
    }

}
