/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.214.0
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InstagramBusinessDiscoveryMediaInner
 */
class InstagramBusinessDiscoveryMediaInnerTest {
    private final InstagramBusinessDiscoveryMediaInner model = new InstagramBusinessDiscoveryMediaInner();

    /**
     * Model tests for InstagramBusinessDiscoveryMediaInner
     */
    @Test
    void testInstagramBusinessDiscoveryMediaInner() {
        // TODO: test InstagramBusinessDiscoveryMediaInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'caption'
     */
    @Test
    void captionTest() {
        // TODO: test caption
    }

    /**
     * Test the property 'mediaType'
     */
    @Test
    void mediaTypeTest() {
        // TODO: test mediaType
    }

    /**
     * Test the property 'mediaProductType'
     */
    @Test
    void mediaProductTypeTest() {
        // TODO: test mediaProductType
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'permalink'
     */
    @Test
    void permalinkTest() {
        // TODO: test permalink
    }

    /**
     * Test the property 'likeCount'
     */
    @Test
    void likeCountTest() {
        // TODO: test likeCount
    }

    /**
     * Test the property 'commentsCount'
     */
    @Test
    void commentsCountTest() {
        // TODO: test commentsCount
    }

}
