/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.ListGoogleBusinessMedia200ResponseMediaItemsInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListGoogleBusinessMedia200Response
 */
class ListGoogleBusinessMedia200ResponseTest {
    private final ListGoogleBusinessMedia200Response model = new ListGoogleBusinessMedia200Response();

    /**
     * Model tests for ListGoogleBusinessMedia200Response
     */
    @Test
    void testListGoogleBusinessMedia200Response() {
        // TODO: test ListGoogleBusinessMedia200Response
    }

    /**
     * Test the property 'success'
     */
    @Test
    void successTest() {
        // TODO: test success
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'locationId'
     */
    @Test
    void locationIdTest() {
        // TODO: test locationId
    }

    /**
     * Test the property 'mediaItems'
     */
    @Test
    void mediaItemsTest() {
        // TODO: test mediaItems
    }

    /**
     * Test the property 'nextPageToken'
     */
    @Test
    void nextPageTokenTest() {
        // TODO: test nextPageToken
    }

    /**
     * Test the property 'totalMediaItemsCount'
     */
    @Test
    void totalMediaItemsCountTest() {
        // TODO: test totalMediaItemsCount
    }

}
