/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListPhoneNumbers200ResponseNumbersInner
 */
class ListPhoneNumbers200ResponseNumbersInnerTest {
    private final ListPhoneNumbers200ResponseNumbersInner model = new ListPhoneNumbers200ResponseNumbersInner();

    /**
     * Model tests for ListPhoneNumbers200ResponseNumbersInner
     */
    @Test
    void testListPhoneNumbers200ResponseNumbersInner() {
        // TODO: test ListPhoneNumbers200ResponseNumbersInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'country'
     */
    @Test
    void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'registrantName'
     */
    @Test
    void registrantNameTest() {
        // TODO: test registrantName
    }

    /**
     * Test the property 'telnyxOrderId'
     */
    @Test
    void telnyxOrderIdTest() {
        // TODO: test telnyxOrderId
    }

    /**
     * Test the property 'monthlyCents'
     */
    @Test
    void monthlyCentsTest() {
        // TODO: test monthlyCents
    }

    /**
     * Test the property 'hostedByZernio'
     */
    @Test
    void hostedByZernioTest() {
        // TODO: test hostedByZernio
    }

    /**
     * Test the property 'profileId'
     */
    @Test
    void profileIdTest() {
        // TODO: test profileId
    }

    /**
     * Test the property 'provisionedAt'
     */
    @Test
    void provisionedAtTest() {
        // TODO: test provisionedAt
    }

    /**
     * Test the property 'metaPreverifiedId'
     */
    @Test
    void metaPreverifiedIdTest() {
        // TODO: test metaPreverifiedId
    }

    /**
     * Test the property 'metaVerificationStatus'
     */
    @Test
    void metaVerificationStatusTest() {
        // TODO: test metaVerificationStatus
    }

    /**
     * Test the property 'onfidoVerificationUrl'
     */
    @Test
    void onfidoVerificationUrlTest() {
        // TODO: test onfidoVerificationUrl
    }

    /**
     * Test the property 'endUserFirstName'
     */
    @Test
    void endUserFirstNameTest() {
        // TODO: test endUserFirstName
    }

    /**
     * Test the property 'endUserLastName'
     */
    @Test
    void endUserLastNameTest() {
        // TODO: test endUserLastName
    }

    /**
     * Test the property 'regulatoryDeclineReason'
     */
    @Test
    void regulatoryDeclineReasonTest() {
        // TODO: test regulatoryDeclineReason
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

}
