/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 
 *
 * The version of the OpenAPI document: 1.134.0
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.RcsBrandInputAddress;
import dev.zernio.model.RcsBrandInputContact;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RcsBrand
 */
class RcsBrandTest {
    private final RcsBrand model = new RcsBrand();

    /**
     * Model tests for RcsBrand
     */
    @Test
    void testRcsBrand() {
        // TODO: test RcsBrand
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'legalName'
     */
    @Test
    void legalNameTest() {
        // TODO: test legalName
    }

    /**
     * Test the property 'legalEntityType'
     */
    @Test
    void legalEntityTypeTest() {
        // TODO: test legalEntityType
    }

    /**
     * Test the property 'organizationType'
     */
    @Test
    void organizationTypeTest() {
        // TODO: test organizationType
    }

    /**
     * Test the property 'websiteUrl'
     */
    @Test
    void websiteUrlTest() {
        // TODO: test websiteUrl
    }

    /**
     * Test the property 'taxId'
     */
    @Test
    void taxIdTest() {
        // TODO: test taxId
    }

    /**
     * Test the property 'stockSymbol'
     */
    @Test
    void stockSymbolTest() {
        // TODO: test stockSymbol
    }

    /**
     * Test the property 'address'
     */
    @Test
    void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'contact'
     */
    @Test
    void contactTest() {
        // TODO: test contact
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

}
