/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UploadWhatsAppNumberKycDocument200Response
 */
class UploadWhatsAppNumberKycDocument200ResponseTest {
    private final UploadWhatsAppNumberKycDocument200Response model = new UploadWhatsAppNumberKycDocument200Response();

    /**
     * Model tests for UploadWhatsAppNumberKycDocument200Response
     */
    @Test
    void testUploadWhatsAppNumberKycDocument200Response() {
        // TODO: test UploadWhatsAppNumberKycDocument200Response
    }

    /**
     * Test the property 'documentId'
     */
    @Test
    void documentIdTest() {
        // TODO: test documentId
    }

}
