/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UsageStatsLimits
 */
class UsageStatsLimitsTest {
    private final UsageStatsLimits model = new UsageStatsLimits();

    /**
     * Model tests for UsageStatsLimits
     */
    @Test
    void testUsageStatsLimits() {
        // TODO: test UsageStatsLimits
    }

    /**
     * Test the property 'uploads'
     */
    @Test
    void uploadsTest() {
        // TODO: test uploads
    }

    /**
     * Test the property 'profiles'
     */
    @Test
    void profilesTest() {
        // TODO: test profiles
    }

}
