/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UsageMeteringTotals
 */
class UsageMeteringTotalsTest {
    private final UsageMeteringTotals model = new UsageMeteringTotals();

    /**
     * Model tests for UsageMeteringTotals
     */
    @Test
    void testUsageMeteringTotals() {
        // TODO: test UsageMeteringTotals
    }

    /**
     * Test the property 'accounts'
     */
    @Test
    void accountsTest() {
        // TODO: test accounts
    }

    /**
     * Test the property 'numbers'
     */
    @Test
    void numbersTest() {
        // TODO: test numbers
    }

    /**
     * Test the property 'calls'
     */
    @Test
    void callsTest() {
        // TODO: test calls
    }

    /**
     * Test the property 'sms'
     */
    @Test
    void smsTest() {
        // TODO: test sms
    }

    /**
     * Test the property 'dlc'
     */
    @Test
    void dlcTest() {
        // TODO: test dlc
    }

    /**
     * Test the property 'xApi'
     */
    @Test
    void xApiTest() {
        // TODO: test xApi
    }

    /**
     * Test the property 'credits'
     */
    @Test
    void creditsTest() {
        // TODO: test credits
    }

    /**
     * Test the property 'other'
     */
    @Test
    void otherTest() {
        // TODO: test other
    }

    /**
     * Test the property 'total'
     */
    @Test
    void totalTest() {
        // TODO: test total
    }

}
