/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ValueRuleCriterion
 */
class ValueRuleCriterionTest {
    private final ValueRuleCriterion model = new ValueRuleCriterion();

    /**
     * Model tests for ValueRuleCriterion
     */
    @Test
    void testValueRuleCriterion() {
        // TODO: test ValueRuleCriterion
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'criteriaType'
     */
    @Test
    void criteriaTypeTest() {
        // TODO: test criteriaType
    }

    /**
     * Test the property 'operator'
     */
    @Test
    void operatorTest() {
        // TODO: test operator
    }

    /**
     * Test the property 'criteriaValues'
     */
    @Test
    void criteriaValuesTest() {
        // TODO: test criteriaValues
    }

    /**
     * Test the property 'criteriaValueTypes'
     */
    @Test
    void criteriaValueTypesTest() {
        // TODO: test criteriaValueTypes
    }

}
