/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.WebhookPayloadPostPlatformAccount;
import dev.zernio.model.WebhookPayloadPostPlatformPlatform;
import dev.zernio.model.WebhookPayloadPostPlatformPost;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WebhookPayloadPostPlatform
 */
class WebhookPayloadPostPlatformTest {
    private final WebhookPayloadPostPlatform model = new WebhookPayloadPostPlatform();

    /**
     * Model tests for WebhookPayloadPostPlatform
     */
    @Test
    void testWebhookPayloadPostPlatform() {
        // TODO: test WebhookPayloadPostPlatform
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'event'
     */
    @Test
    void eventTest() {
        // TODO: test event
    }

    /**
     * Test the property 'post'
     */
    @Test
    void postTest() {
        // TODO: test post
    }

    /**
     * Test the property 'platform'
     */
    @Test
    void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'account'
     */
    @Test
    void accountTest() {
        // TODO: test account
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    void timestampTest() {
        // TODO: test timestamp
    }

}
