/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AnalyticsSinglePostResponseMediaItemsInner
 */
class AnalyticsSinglePostResponseMediaItemsInnerTest {
    private final AnalyticsSinglePostResponseMediaItemsInner model = new AnalyticsSinglePostResponseMediaItemsInner();

    /**
     * Model tests for AnalyticsSinglePostResponseMediaItemsInner
     */
    @Test
    void testAnalyticsSinglePostResponseMediaItemsInner() {
        // TODO: test AnalyticsSinglePostResponseMediaItemsInner
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'url'
     */
    @Test
    void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'thumbnail'
     */
    @Test
    void thumbnailTest() {
        // TODO: test thumbnail
    }

}
