/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.api;

import dev.zernio.ApiException;
import dev.zernio.model.CreateAdInsightsReport202Response;
import dev.zernio.model.CreateAdInsightsReportRequest;
import dev.zernio.model.ErrorResponse;
import dev.zernio.model.GetAdAnalytics200Response;
import dev.zernio.model.GetAdInsightsReport200Response;
import dev.zernio.model.GetCampaignAnalytics200Response;
import dev.zernio.model.InlineObject;
import dev.zernio.model.InlineObject1;
import java.time.LocalDate;
import dev.zernio.model.QueryAdInsights200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for AdInsightsApi
 */
@Disabled
public class AdInsightsApiTest {

    private final AdInsightsApi api = new AdInsightsApi();

    
    /**
     * Submit an async insights report run
     *
     * Submits an asynchronous Meta insights report. Same query surface as GET /v1/ads/insights, but in the JSON body; Meta processes the report server-side, which is the right choice for long ranges or large accounts where the sync query is slow or rate-limited. Returns a &#x60;reportRunId&#x60; to poll via GET /v1/ads/insights/reports/{reportRunId}. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAdInsightsReportTest() throws ApiException {
        CreateAdInsightsReportRequest createAdInsightsReportRequest = null;
        CreateAdInsightsReport202Response response = 
        api.createAdInsightsReport(createAdInsightsReportRequest);
        
        // TODO: test validations
    }
    
    /**
     * Get ad analytics
     *
     * Returns detailed performance analytics for an ad. Includes summary metrics, a daily timeline over the requested date range, and optional demographic breakdowns (Meta and TikTok only). If no date range is provided, defaults to the last 90 days. Date range is capped at 730 days max. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAdAnalyticsTest() throws ApiException {
        String adId = null;
        LocalDate fromDate = null;
        LocalDate toDate = null;
        String breakdowns = null;
        GetAdAnalytics200Response response = 
        api.getAdAnalytics(adId, fromDate, toDate, breakdowns);
        
        // TODO: test validations
    }
    
    /**
     * Poll an async insights report run
     *
     * Status and results for a report run created via POST /v1/ads/insights/reports. While the job runs, returns &#x60;status&#x60; and &#x60;percentCompletion&#x60;. Once &#x60;status&#x60; is \&quot;Job Completed\&quot; the response also carries a &#x60;data&#x60; page, cursor-paginated via &#x60;limit&#x60; / &#x60;after&#x60;. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAdInsightsReportTest() throws ApiException {
        String reportRunId = null;
        String accountId = null;
        Integer limit = null;
        String after = null;
        GetAdInsightsReport200Response response = 
        api.getAdInsightsReport(reportRunId, accountId, limit, after);
        
        // TODO: test validations
    }
    
    /**
     * Get campaign analytics
     *
     * Returns performance analytics for a whole campaign in one call: summary metrics, a daily timeline over the requested date range (summed across the campaign&#39;s ads), and optional demographic breakdowns. Breakdowns are fetched live from Meta at the campaign level (one call per dimension, no per-ad fan-out), so an agency dashboard gets campaign-level age/gender/etc. without summing thousands of per-ad reads. &#x60;campaignId&#x60; is the platform campaign id; pass &#x60;platform&#x60; when a campaign id could be ambiguous across platforms. If no date range is provided, defaults to the last 90 days. Date range is capped at 730 days max. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCampaignAnalyticsTest() throws ApiException {
        String campaignId = null;
        String platform = null;
        LocalDate fromDate = null;
        LocalDate toDate = null;
        String breakdowns = null;
        GetCampaignAnalytics200Response response = 
        api.getCampaignAnalytics(campaignId, platform, fromDate, toDate, breakdowns);
        
        // TODO: test validations
    }
    
    /**
     * Flexible live insights query
     *
     * Live, flexible insights query against Meta&#39;s Graph API. Unlike GET /v1/ads/{adId}/analytics (fixed metric set, cached), this forwards caller-chosen &#x60;fields&#x60;, &#x60;breakdowns&#x60; and &#x60;filtering&#x60; to any Meta insights node and returns Meta&#39;s rows verbatim.  &#x60;objectId&#x60; selects the node: an ad account, campaign, ad set or ad platform id. &#x60;level&#x60; sets row granularity independently of the node.  Semantic validation is Meta&#39;s: an unknown field or invalid breakdown combination returns a 400 carrying Meta&#39;s message. For long ranges or agency-scale accounts prefer the async variant (POST /v1/ads/insights/reports). 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryAdInsightsTest() throws ApiException {
        String accountId = null;
        String objectId = null;
        String level = null;
        String fields = null;
        String breakdowns = null;
        String actionBreakdowns = null;
        String actionAttributionWindows = null;
        String actionReportTime = null;
        Boolean useUnifiedAttributionSetting = null;
        String filtering = null;
        String datePreset = null;
        LocalDate fromDate = null;
        LocalDate toDate = null;
        String timeIncrement = null;
        Integer limit = null;
        String after = null;
        QueryAdInsights200Response response = 
        api.queryAdInsights(accountId, objectId, level, fields, breakdowns, actionBreakdowns, actionAttributionWindows, actionReportTime, useUnifiedAttributionSetting, filtering, datePreset, fromDate, toDate, timeIncrement, limit, after);
        
        // TODO: test validations
    }
    
}
