/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.getlate.api;

import dev.getlate.ApiClient;
import dev.getlate.ApiException;
import dev.getlate.ApiResponse;
import dev.getlate.Configuration;
import dev.getlate.Pair;

import dev.getlate.model.CreateAccountGroup201Response;
import dev.getlate.model.CreateAccountGroupRequest;
import dev.getlate.model.DeleteAccountGroup200Response;
import dev.getlate.model.InlineObject;
import dev.getlate.model.InlineObject1;
import dev.getlate.model.ListAccountGroups200Response;
import dev.getlate.model.UpdateAccountGroup200Response;
import dev.getlate.model.UpdateAccountGroupRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-16T12:16:29.249907297Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class AccountGroupsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public AccountGroupsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public AccountGroupsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Create group
   * Creates a new account group with a name and a list of social account IDs.
   * @param createAccountGroupRequest  (required)
   * @return CreateAccountGroup201Response
   * @throws ApiException if fails to make API call
   */
  public CreateAccountGroup201Response createAccountGroup(@javax.annotation.Nonnull CreateAccountGroupRequest createAccountGroupRequest) throws ApiException {
    return createAccountGroup(createAccountGroupRequest, null);
  }

  /**
   * Create group
   * Creates a new account group with a name and a list of social account IDs.
   * @param createAccountGroupRequest  (required)
   * @param headers Optional headers to include in the request
   * @return CreateAccountGroup201Response
   * @throws ApiException if fails to make API call
   */
  public CreateAccountGroup201Response createAccountGroup(@javax.annotation.Nonnull CreateAccountGroupRequest createAccountGroupRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateAccountGroup201Response> localVarResponse = createAccountGroupWithHttpInfo(createAccountGroupRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Create group
   * Creates a new account group with a name and a list of social account IDs.
   * @param createAccountGroupRequest  (required)
   * @return ApiResponse&lt;CreateAccountGroup201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateAccountGroup201Response> createAccountGroupWithHttpInfo(@javax.annotation.Nonnull CreateAccountGroupRequest createAccountGroupRequest) throws ApiException {
    return createAccountGroupWithHttpInfo(createAccountGroupRequest, null);
  }

  /**
   * Create group
   * Creates a new account group with a name and a list of social account IDs.
   * @param createAccountGroupRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateAccountGroup201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateAccountGroup201Response> createAccountGroupWithHttpInfo(@javax.annotation.Nonnull CreateAccountGroupRequest createAccountGroupRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createAccountGroupRequestBuilder(createAccountGroupRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createAccountGroup", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateAccountGroup201Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateAccountGroup201Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateAccountGroup201Response>() {});
        

        return new ApiResponse<CreateAccountGroup201Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createAccountGroupRequestBuilder(@javax.annotation.Nonnull CreateAccountGroupRequest createAccountGroupRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'createAccountGroupRequest' is set
    if (createAccountGroupRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'createAccountGroupRequest' when calling createAccountGroup");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/account-groups";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(createAccountGroupRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete group
   * Permanently deletes an account group. The accounts themselves are not affected.
   * @param groupId  (required)
   * @return DeleteAccountGroup200Response
   * @throws ApiException if fails to make API call
   */
  public DeleteAccountGroup200Response deleteAccountGroup(@javax.annotation.Nonnull String groupId) throws ApiException {
    return deleteAccountGroup(groupId, null);
  }

  /**
   * Delete group
   * Permanently deletes an account group. The accounts themselves are not affected.
   * @param groupId  (required)
   * @param headers Optional headers to include in the request
   * @return DeleteAccountGroup200Response
   * @throws ApiException if fails to make API call
   */
  public DeleteAccountGroup200Response deleteAccountGroup(@javax.annotation.Nonnull String groupId, Map<String, String> headers) throws ApiException {
    ApiResponse<DeleteAccountGroup200Response> localVarResponse = deleteAccountGroupWithHttpInfo(groupId, headers);
    return localVarResponse.getData();
  }

  /**
   * Delete group
   * Permanently deletes an account group. The accounts themselves are not affected.
   * @param groupId  (required)
   * @return ApiResponse&lt;DeleteAccountGroup200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DeleteAccountGroup200Response> deleteAccountGroupWithHttpInfo(@javax.annotation.Nonnull String groupId) throws ApiException {
    return deleteAccountGroupWithHttpInfo(groupId, null);
  }

  /**
   * Delete group
   * Permanently deletes an account group. The accounts themselves are not affected.
   * @param groupId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DeleteAccountGroup200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DeleteAccountGroup200Response> deleteAccountGroupWithHttpInfo(@javax.annotation.Nonnull String groupId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteAccountGroupRequestBuilder(groupId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteAccountGroup", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DeleteAccountGroup200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DeleteAccountGroup200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DeleteAccountGroup200Response>() {});
        

        return new ApiResponse<DeleteAccountGroup200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteAccountGroupRequestBuilder(@javax.annotation.Nonnull String groupId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'groupId' is set
    if (groupId == null) {
      throw new ApiException(400, "Missing the required parameter 'groupId' when calling deleteAccountGroup");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/account-groups/{groupId}"
        .replace("{groupId}", ApiClient.urlEncode(groupId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List groups
   * Returns all account groups for the authenticated user, including group names and associated account IDs.
   * @return ListAccountGroups200Response
   * @throws ApiException if fails to make API call
   */
  public ListAccountGroups200Response listAccountGroups() throws ApiException {
    return listAccountGroups(null);
  }

  /**
   * List groups
   * Returns all account groups for the authenticated user, including group names and associated account IDs.
   * @param headers Optional headers to include in the request
   * @return ListAccountGroups200Response
   * @throws ApiException if fails to make API call
   */
  public ListAccountGroups200Response listAccountGroups(Map<String, String> headers) throws ApiException {
    ApiResponse<ListAccountGroups200Response> localVarResponse = listAccountGroupsWithHttpInfo(headers);
    return localVarResponse.getData();
  }

  /**
   * List groups
   * Returns all account groups for the authenticated user, including group names and associated account IDs.
   * @return ApiResponse&lt;ListAccountGroups200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ListAccountGroups200Response> listAccountGroupsWithHttpInfo() throws ApiException {
    return listAccountGroupsWithHttpInfo(null);
  }

  /**
   * List groups
   * Returns all account groups for the authenticated user, including group names and associated account IDs.
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ListAccountGroups200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ListAccountGroups200Response> listAccountGroupsWithHttpInfo(Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listAccountGroupsRequestBuilder(headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listAccountGroups", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ListAccountGroups200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ListAccountGroups200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ListAccountGroups200Response>() {});
        

        return new ApiResponse<ListAccountGroups200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listAccountGroupsRequestBuilder(Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/account-groups";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update group
   * Updates the name or account list of an existing group. You can rename the group, change its accounts, or both.
   * @param groupId  (required)
   * @param updateAccountGroupRequest  (required)
   * @return UpdateAccountGroup200Response
   * @throws ApiException if fails to make API call
   */
  public UpdateAccountGroup200Response updateAccountGroup(@javax.annotation.Nonnull String groupId, @javax.annotation.Nonnull UpdateAccountGroupRequest updateAccountGroupRequest) throws ApiException {
    return updateAccountGroup(groupId, updateAccountGroupRequest, null);
  }

  /**
   * Update group
   * Updates the name or account list of an existing group. You can rename the group, change its accounts, or both.
   * @param groupId  (required)
   * @param updateAccountGroupRequest  (required)
   * @param headers Optional headers to include in the request
   * @return UpdateAccountGroup200Response
   * @throws ApiException if fails to make API call
   */
  public UpdateAccountGroup200Response updateAccountGroup(@javax.annotation.Nonnull String groupId, @javax.annotation.Nonnull UpdateAccountGroupRequest updateAccountGroupRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<UpdateAccountGroup200Response> localVarResponse = updateAccountGroupWithHttpInfo(groupId, updateAccountGroupRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Update group
   * Updates the name or account list of an existing group. You can rename the group, change its accounts, or both.
   * @param groupId  (required)
   * @param updateAccountGroupRequest  (required)
   * @return ApiResponse&lt;UpdateAccountGroup200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UpdateAccountGroup200Response> updateAccountGroupWithHttpInfo(@javax.annotation.Nonnull String groupId, @javax.annotation.Nonnull UpdateAccountGroupRequest updateAccountGroupRequest) throws ApiException {
    return updateAccountGroupWithHttpInfo(groupId, updateAccountGroupRequest, null);
  }

  /**
   * Update group
   * Updates the name or account list of an existing group. You can rename the group, change its accounts, or both.
   * @param groupId  (required)
   * @param updateAccountGroupRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;UpdateAccountGroup200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UpdateAccountGroup200Response> updateAccountGroupWithHttpInfo(@javax.annotation.Nonnull String groupId, @javax.annotation.Nonnull UpdateAccountGroupRequest updateAccountGroupRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateAccountGroupRequestBuilder(groupId, updateAccountGroupRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateAccountGroup", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<UpdateAccountGroup200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        UpdateAccountGroup200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<UpdateAccountGroup200Response>() {});
        

        return new ApiResponse<UpdateAccountGroup200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateAccountGroupRequestBuilder(@javax.annotation.Nonnull String groupId, @javax.annotation.Nonnull UpdateAccountGroupRequest updateAccountGroupRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'groupId' is set
    if (groupId == null) {
      throw new ApiException(400, "Missing the required parameter 'groupId' when calling updateAccountGroup");
    }
    // verify the required parameter 'updateAccountGroupRequest' is set
    if (updateAccountGroupRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'updateAccountGroupRequest' when calling updateAccountGroup");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/account-groups/{groupId}"
        .replace("{groupId}", ApiClient.urlEncode(groupId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(updateAccountGroupRequest);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
